### ISSUE TITLE
No Cancel Option when trimming sound

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#963] opened 2017-11-28 23:24 UTC
While playing around with the sounds menu I clicked on the trim tool and realized that there was no option but to save it.  If the user decides to cancel or clicks it by accident the only option is to trim and then undo.

When I make a UX suggestion I always try to include a mockup of what I mean but I am stumped on this one.  Where/how would a cancel action be triggered?  The button already transforms into the save button so a new button would have to appear which would then move the undo/redo buttons to a new location which in turn could lead to confusion.

**Comment by paulkaplan** [comment] 2017-11-30 14:43
Thanks for reporting this, however I'm going to close this as a duplicate of https://github.com/LLK/scratch-gui/issues/582

**Closed by paulkaplan** 2017-11-30 14:43 UTC
Labels: design, needs-discussion
