### ISSUE TITLE
ios safari after downloading a project fails you leave the page and lose work

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4030] opened 2018-12-12 18:41 UTC
@kathymakes writes:
Because downloading doesn’t work on iOS devices, you get redirected to a safari error screen and you lose your work :( Ideally it should open a new tab -or- tell the user download doesn’t work -or- maybe do nothing

### Steps to Reproduce

on ipad create a new project
make a few changes
Choose File>download to your computer
Note: you are taken to an error page
Your project is now gone

### Operating System and Browser

Safari on ios

**Comment by tomrow** [comment] 2018-12-13 08:46
Possibly if we wanted to be really lazy we could just make the project save before attempting the download

**Comment by kchadha** [comment] 2020-04-08 15:00
Dupe of #1783

**Closed by kchadha** 2020-04-08 15:00 UTC
Labels: bug, ios, needs triage
