### ISSUE TITLE
You can make multiple custom procedures with the same name

### ISSUE THREAD

**Issue by owenkaplinsky** [LLK/scratch-gui#9570] opened 2024-04-13 18:19 UTC
### Expected Behavior

When you try to make a custom procedure with a name that already exists, it should have a popup that says that there already is a custom procedure with that name

### Actual Behavior

Making a new custom procedure with a name that a custom procedure already has does not prevent you from creating it

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Create a custom procedure
2. Create another custom procedure with the same name
3. Observe how you are allowed to create it

### System Details
All

**Screenshots**
![image](https://github.com/scratchfoundation/scratch-gui/assets/138824486/b61f29f6-9d0c-4b45-aed2-8642f6d37fe7)

**Comment by Secret-chest** [comment] 2024-04-13 18:37
Same name but different fields should be allowed.

**Comment by alexcui03** [comment] 2024-08-06 20:44
Duplicate of #1650

**Closed as not planned** 2024-08-22 18:06 UTC
