### ISSUE TITLE
Lists don't show correctly

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1370] opened 2018-01-30 00:13 UTC
### Expected Behavior

You should be able to see the list and manipulate the list with buttons in the list like in Scratch 2.

### Actual Behavior

It displays like a variable and you can't change anything.
![datamonitor](https://user-images.githubusercontent.com/33498997/35541350-54553712-0528-11e8-8999-db0e8c27374a.PNG)

### Steps to Reproduce

1. Make a list.
2. Add items to list with blocks (optional).
3. Show the list monitor with the check mark in the blocks menu.

### Operating System and Browser

Windows 10 on Chrome

**Comment by paulkaplan** [comment] 2018-01-30 16:02
Closing as a duplicate of https://github.com/LLK/scratch-gui/issues/942

**Closed by paulkaplan** 2018-01-30 16:02 UTC
