### ISSUE TITLE
SVGs created with Inkscape don't render/import properly

### ISSUE THREAD

**Issue by astrosticks** [LLK/scratch-gui#6101] opened 2020-08-18 23:18 UTC
### Expected Behavior

Importing an SVG created in Inkscape should create a costume that looks identical to how the file itself appears in a browser.

### Actual Behavior

Two problems arise:

1. The objects will not appear in the same relative region of the document as they did in Inkscape (misaligned).

2. The costume will not actually render in the project viewport until changing it in some way in the vector editor.

### Steps to Reproduce

Create an SVG in Inkscape with dimensions of 480 x 360 px. Add objects to the scene. Save and upload to Scratch as a sprite costume. 

To get the costume to appear in the stage, just use the move tool in the vector editor and move it around slightly.

### Operating System and Browser

Ubuntu 20.04 with Firefox. Also tested on Windows 10 with Firefox. Issue has persisted through last few versions of Inkscape.

___

**Why Scratch should support Inkscape SVGs**: Inkscape SVGs render properly in all modern browsers and image viewing programs. As Inkscape very rigorously sticks to the SVG specification, there is presumably no problem with how measurements and coordinates are written when exporting, so if Scratch is failing to display Inkscape SVGs, then SVG imports as a whole aren't working correctly (only a hunch, but it's hard to verify). Additionally, Inkscape is the best free/open-source option for users who don't have access to expensive vector drawing tools such as Adobe Illustrator (whose SVGs do import correctly at the time of writing).

### Screenshots

**Inkscape**
![image](https://user-images.githubusercontent.com/32315760/90574217-f96c3000-e17d-11ea-8b0f-3c98a836fe5e.png)
**scratch-gui** running locally
![image](https://user-images.githubusercontent.com/32315760/90574619-09384400-e17f-11ea-978c-18149b175e49.png)

**Comment by astrosticks** [comment] 2020-08-19 01:23
Even if this isn't a high-priority issue, I'd really appreciate it if someone could help lead me down the trail to where this problem might exist in the source so that I can take a look at it :smiley:

**Comment by BryceLTaylor** [comment] 2020-08-20 19:30
duplicate of https://github.com/LLK/scratch-gui/issues/4711

**Closed as completed** 2020-11-12 22:10 UTC
Labels: Low Impact
