### ISSUE TITLE
Add keyboard controls for paint editor

### ISSUE THREAD

**Issue by quachtina96** [LLK/scratch-gui#1045] opened 2017-12-15 19:39 UTC
### Expected Behavior
As someone used to using keyboard controls for editing images and text, I instinctively tried to use
Ctrl + Z to undo changes in the paint editor
Ctrl + C to copy
Ctrl + P to paste

### Actual Behavior
Nothing happens when you use these key controls.

**Comment by fsih** [comment] 2017-12-20 15:39
Dupe of https://github.com/LLK/scratch-paint/issues/38

**Closed by fsih** 2017-12-20 15:39 UTC
Labels: accessibility, feature, help wanted
