### ISSUE TITLE
Bitmap Paintbrush with no fill

### ISSUE THREAD

**Issue by chexbox** [LLK/scratch-gui#2408] opened 2018-06-19 22:10 UTC
### Expected Behavior
The paintbrush should have no fill if fill is set to none.

### Actual Behavior
paintbrush paints black:
![2018-06-19-170404_514x451_scrot](https://user-images.githubusercontent.com/31783961/41626784-0fce500e-73e3-11e8-9d83-2cd0118d5459.png)

### Steps to Reproduce
Convert to bitmap, set the paintbrush fill to none, and scribble away.

### Operating System and Browser
Chrome, Raspian

Edit: Oops, I intended to put this on scratch-paint.

**Comment by hedgehog125** [comment] 2018-06-20 06:51
Shouldn't it be changed to line colour or something?

**Comment by apple502j** [comment] 2018-06-20 08:37
Shouldn't it be in LLK/scratch-paint ?

**Comment by chexbox** [comment] 2018-06-20 18:46
@hedgehog125 No, I was showing the black line painted with the brush fill set to 'none'

**Comment by thisandagain** [comment] 2018-06-20 19:06
From design discussion: the paint tool when the fill is set to "transparent" should operate like the eraser.

**Comment by fsih** [comment] 2018-06-27 14:36
Duplicate of https://github.com/LLK/scratch-paint/issues/535

**Closed by fsih** 2018-06-27 14:36 UTC
Labels: feature
