### ISSUE TITLE
Sprite 'tile' image and text is selectable

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#297] opened 2017-04-04 15:30 UTC
### Expected Behavior

Sprite tile image and text should not be selectable

### Actual Behavior

Multiple times during the play test folks tried to drag the sprite tiles (which is a separate feature https://github.com/LLK/scratch-gui/issues/161) or click the sprite tile resulting in the sprite name and/or the image became highlighted.

![text-highlight](https://cloud.githubusercontent.com/assets/3409578/24664585/0fbc6fa8-1929-11e7-94e3-69869f9632c9.gif)

![text-image-highlight](https://cloud.githubusercontent.com/assets/3409578/24664720/63221940-1929-11e7-844d-dbdcea437545.gif)

In this case some of the sprite info gets highlighted too.
![text-image-info-highlight](https://cloud.githubusercontent.com/assets/3409578/24664725/66baa428-1929-11e7-99d3-d26fd2d796b4.gif)

This can also happen within the sprite library.
![brazil_16 27-sprite-highlight-library mp4](https://cloud.githubusercontent.com/assets/3409578/24664860/b497129e-1929-11e7-8431-30c7a9dd1a11.gif)

<img width="1221" alt="italy_17 30-sprite-highlight-library-still" src="https://cloud.githubusercontent.com/assets/3409578/24664905/d0ebcf48-1929-11e7-86fd-aa2223d9c106.png">

Sometimes the you can even drag the image from within the tile.
![dragging-letter](https://cloud.githubusercontent.com/assets/3409578/24665002/143a2b50-192a-11e7-9c68-c0186eff827b.gif)

**Comment by navignaw** [comment] 2017-04-12 00:56
Looks like a dupe of #162, which was fixed in #234 for Chrome and Firefox.

Just to double-check, which browser(s) did you reproduce the issue on?

**Comment by thisandagain** [comment] 2018-02-01 23:25
Resolved in #234

**Closed by thisandagain** 2018-02-01 23:25 UTC
Labels: bug, help wanted
