### ISSUE TITLE
Error on painting a sprite or adding empty sprite

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#2024] opened 2018-05-10 15:22 UTC
### Expected Behavior

No errors

### Actual Behavior

When you paint a new sprite or add a sprite with an empty costume, you get console errors:

`WebGL: INVALID_VALUE: texImage2D: no canvas`
`Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`
`[.Offscreen-For-WebGL-0x7f8ad303f800]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips`
`[.Offscreen-For-WebGL-0x7f8ad303f800]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.`

### Steps to Reproduce

Either:

- paint a new sprite.

Or

- from the sprite library, add the 'empty' sprite.

**Comment by paulkaplan** [comment] 2018-05-10 18:19
This is a duplicate of https://github.com/LLK/scratch-render/issues/242

**Closed** 2018-05-10 18:19 UTC
Labels: bug
