### ISSUE TITLE
Sound editor looks weird in non-Chrome

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#657] opened 2017-08-30 20:32 UTC
### Expected Behavior

_Please describe what should happen_
Sound editor should look about the same in all browsers

Chrome on Windows:
![image](https://user-images.githubusercontent.com/2855464/29893501-47ff13b6-8da0-11e7-9bf8-2f1fba8d1384.png)

### Actual Behavior

_Describe what actually happens_
Edge on Windows:
![image](https://user-images.githubusercontent.com/2855464/29893468-2d4376ac-8da0-11e7-8109-962349cd340b.png)
Meow image is huuuuge
Sound editor is huuuge

Firefox on Windows:
![image](https://user-images.githubusercontent.com/2855464/29893539-5b684b5c-8da0-11e7-930c-3373e42edba4.png)
Graph not rendering
Graph and effect buttons flow under stage

**Comment by chooper100** [comment] 2017-08-30 22:55
Can for Edge 40,15063.0.0 reproduce on Windows 10 version 1703

**Comment by towerofnix** [comment] 2017-08-31 20:19
Firefox on Windows looks the same as Firefox on Linux/Debian, for what it's worth.

**Comment by thisandagain** [comment] 2017-09-03 22:58
@paulkaplan @rschamp Should we create a new label to track issued related to Edge?

**Comment by paulkaplan** [comment] 2017-09-05 12:24
Yeah probably a good idea to start labeling them with browsers individually.

**Comment by thisandagain** [comment] 2017-09-05 15:44
Done! Note: this issue seems to be isolated to Edge and Firefox (Chrome and Safari look ok).

**Comment by bartljak** [comment] 2017-09-26 19:28
Sound block looks huge on Safari and Chrome on macOS 10.12.6 for me. 
![screen shot 2017-09-26 at 3 27 18 pm](https://user-images.githubusercontent.com/6947753/30880054-5b4335e4-a2cf-11e7-9cd4-3f5d44c16132.png)

**Comment by stdio2016** [comment] 2017-11-19 04:22
in firefox maybe because svg <path d> contains comma, and firefox hates that

**Comment by thisandagain** [comment] 2017-12-20 16:03
Resolved in #915

**Closed by thisandagain** 2017-12-20 16:03 UTC
Labels: bug, edge, firefox, has-patch, help wanted
