### ISSUE TITLE
when input of import csv cancel,the input element should be hidden

### ISSUE THREAD

**Issue by Aaron-jo** [LLK/scratch-gui#7960] opened 2022-01-13 10:18 UTC
### Expected Behavior

when input of import csv cancel,the input element should be hidden

### Actual Behavior

When importing a .csv file to a list, user presses cancel button of browser prompt. This will result in Input Element not being removed

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://scratch.mit.edu/projects/editor/?tutorial=getStarted'
2. Open a monitor of list`s variable
3. Right Click this monitor and select import menu
4. Cancel import
5. Input element is not destroyed

### System Details
Mac
 * [x] Chrome 97.0.4692.71
 * [ ] Firefox 
 * [ ] Safari

Windows
 * [x] Chrome 
 * [ ] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/12815298/145607626-1329d3f9-21fc-4c90-83cd-c0f6ed9387f3.png)

**Comment by apple502j** [comment] 2022-01-13 15:10
Duplicate of #4681

**Comment by BryceLTaylor** [comment] 2022-01-13 21:23
Closing as duplicate

**Closed as completed by BryceLTaylor** 2022-01-13 21:23 UTC
