### ISSUE TITLE
Issue found in Bug Hunt on 11/2/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3640] opened 2018-11-05 19:21 UTC
* [x] I can’t keep the language menu open on Firefox… Menu is scared of being hovered over. @kathymakes
![image20](https://user-images.githubusercontent.com/1088291/48021135-d33ee280-e105-11e8-8fb3-2e5a2e7ed732.gif)
* [x] Can’t use language selector in Firefox @fsih 
![image8](https://user-images.githubusercontent.com/1088291/48021026-7c390d80-e105-11e8-8667-2529021d2b9e.gif)
* [ ] Blocks overlapped by categories after switching languages @fsih 
![image6](https://user-images.githubusercontent.com/1088291/48021074-a8548e80-e105-11e8-9192-86529bb51021.png)
* [x] In a non-english language, the default name for a boolean argument is still “boolean” but should be translated @paulkaplan 
* [ ] Ipad safari: I don’t have a good repro case, but twice during the bug hunt switching to spanish crashed. Once while I had custom procedures on the screen. @picklesrus 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Eric R
Mac | Chrome | ChrisG
iPad** | Safari | Karishma
Chromebook | Chrome | Carl
Windows* | Firefox | DD
Android Tablet | Chrome | Ben
Windows* | Edge | Bryce
Mac | Safari | Andrew
Mac | Firefox | kathy

**Comment by Kenny2github** [comment] 2018-11-06 09:10
> * [ ]  I can’t keep the language menu open on Firefox… Menu is scared of being hovered over. @kathymakes
>   ![image20](https://user-images.githubusercontent.com/1088291/48021135-d33ee280-e105-11e8-8fb3-2e5a2e7ed732.gif)
> * [ ]  Can’t use language selector in Firefox @fsih
>   ![image8](https://user-images.githubusercontent.com/1088291/48021026-7c390d80-e105-11e8-8667-2529021d2b9e.gif)

These are duplicates of each other

**Comment by apple502j** [comment] 2018-11-06 12:59
> 
> 
> > * [ ]   I can’t keep the language menu open on Firefox… Menu is scared of being hovered over. 
> > * [ ]   Can’t use language selector in Firefox 
> 
> These are duplicates of each other

Dupe of #3613 and confirmed it's fixed now

**Comment by chrisgarrity** [comment] 2018-11-06 15:41
I wasn't able to duplicate the overlapping category issue (nor was @fsih) so we'll wait to see if it comes up again with a reliable repro case

**Comment by chrisgarrity** [comment] 2019-02-04 12:42
Was never able to repro the other cases. Closing this issue.

**Closed by chrisgarrity** 2019-02-04 12:42 UTC
Labels: needs-repro, smoke-testing
