### ISSUE TITLE
Stop button transition isn't smooth

### ISSUE THREAD

**Issue by kerrtravers** [LLK/scratch-gui#750] opened 2017-10-09 19:53 UTC
### Expected Behavior
When hovering over the stop button with your mouse, It zooms in smoothly like the green flag.

### Actual Behavior
When hovered over, the stop button zooms in but then moves over to the bottom right slightly.

### Steps to Reproduce
- Go to the editor 
- Hover over both the green flag and the stop button
- Compare the animations

### Operating System and Browser
Windows 8.1 (Chrome)

**Comment by towerofnix** [comment] 2017-10-10 01:19
I can't reproduce this on Firefox 52.3.0 (on Linux/Debian). It zooms as you'd expect.

**Comment by Kenny2github** [comment] 2017-10-10 02:01
I can't reproduce this on Chromium 57 on Raspbian (Debian Linux).

However, I do see that the _green flag_ jitters while expanding - _not_ the stop button. I think that both of the icons have the same problem, but it's OS/browser-specific which one has problems.

**Comment by VutonDesign** [comment] 2017-10-10 07:04
It'a definitely OS/browser-specific then...

**Comment by thisandagain** [comment] 2017-10-10 10:10
I can't reproduce this on Chrome 61.0.3163.100 on MacOS 10.12.6. Because this appears to be OS / browser specific can you please provide more details about your version of Chrome @VutonDesign?

**Comment by VutonDesign** [comment] 2017-10-10 14:41
@thisandagain The exact version specs would be:
>  Google Chrome 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)

This is quite a small bug, I'm surprised it noticed it actually.

**Comment by Kenny2github** [comment] 2017-10-11 00:30
@VutonDesign in that case it seems like it’s OS-specific, not browser specific - specifically, windows jitters the green flag, and Raspbian jitters the stop button. Wonder what’s causing it?

**Comment by VutonDesign** [comment] 2017-10-11 07:12
@Kenny2github Yeah, I'm not too sure...

**Comment by paulkaplan** [comment] 2019-08-02 13:45
There is no longer a zoom transition, so closing this issue.

**Closed by paulkaplan** 2019-08-02 13:45 UTC
Labels: bug, needs-info
