### ISSUE TITLE
Meet error while visit the GUI locally

### ISSUE THREAD

**Issue by tayoka** [LLK/scratch-gui#956] opened 2017-11-28 08:15 UTC
### Expected Behavior

I started the server successfully after running npm start, and tried to visit the GUI with http://localhost:8601/.

### Actual Behavior
I met following errors while rendering the page.

ERROR in ./node_modules/scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'dgram' in '/Users/yoka/yoka_ws/scratch/scratch-gui/node_modules/scratch-vm/dist/node'
 @ ./node_modules/scratch-vm/dist/node/scratch-vm.js 56510:17-33
 @ ./src/containers/controls.jsx
 @ ./src/examples/blocks-only.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/examples/blocks-only.jsx

ERROR in ./node_modules/scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'dns' in '/Users/yoka/yoka_ws/scratch/scratch-gui/node_modules/scratch-vm/dist/node'
 @ ./node_modules/scratch-vm/dist/node/scratch-vm.js 56516:17-31
 @ ./src/containers/controls.jsx
 @ ./src/examples/blocks-only.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/examples/blocks-only.jsx

ERROR in ./node_modules/scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'fs' in '/Users/yoka/yoka_ws/scratch/scratch-gui/node_modules/scratch-vm/dist/node'
 @ ./node_modules/scratch-vm/dist/node/scratch-vm.js 27654:17-30
 @ ./src/containers/controls.jsx
 @ ./src/examples/blocks-only.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/examples/blocks-only.jsx

ERROR in ./node_modules/scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'net' in '/Users/yoka/yoka_ws/scratch/scratch-gui/node_modules/scratch-vm/dist/node'
 @ ./node_modules/scratch-vm/dist/node/scratch-vm.js 19786:17-31
 @ ./src/containers/controls.jsx
 @ ./src/examples/blocks-only.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/examples/blocks-only.jsx

ERROR in ./node_modules/scratch-vm/dist/node/scratch-vm.js
Module not found: Error: Can't resolve 'tls' in '/Users/yoka/yoka_ws/scratch/scratch-gui/node_modules/scratch-vm/dist/node'
 @ ./node_modules/scratch-vm/dist/node/scratch-vm.js 27672:17-31
 @ ./src/containers/controls.jsx
 @ ./src/examples/blocks-only.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/examples/blocks-only.jsx

### Steps to Reproduce

1. git clone the project
2. run npm install without errors
3. open http://localhost:8601, and I get a blank page & errors above in terminal.

### Operating System and Browser

_e.g. Mac OS 10.11.4 Chrome 62.0.3202.89

**Comment by Rewarp** [comment] 2017-11-28 11:20
I can confirm the error when installed on Ubuntu Desktop 17.10 running as a server. Nothing is displayed in Firefox 57.

**Comment by theist** [comment] 2017-11-28 11:45
Same here on a debian 9 / chrome browser npm version 5.5.1 node version 8.9.1

**Comment by Kenny2github** [comment] 2017-11-28 12:40
As per above comments, this is obviously not browser specific.

**Comment by thisandagain** [comment] 2017-11-28 12:41
@paulkaplan Looks like something may be breaking the build. Can you take a look?

**Comment by thisandagain** [comment] 2017-11-28 12:45
This may be related to https://github.com/LLK/scratch-vm/pull/823 will re-run the GUI build in travis after landing https://github.com/LLK/scratch-vm/pull/823

**Comment by thisandagain** [comment] 2017-11-28 12:53
Hi @tayoka, sorry for the trouble. A bugfix for the VM (LLK/scratch-vm#823) has landed. Would you mind doing an `rm -rf node_modules && npm install` and trying again?

**Closed** 2017-11-28 13:01 UTC
Labels: bug, ergonomics

**Comment by theist** [comment] 2017-11-28 19:09
> Hi @tayoka, sorry for the trouble. A bugfix for the VM (LLK/scratch-vm#823) has landed. Would you mind doing an rm -rf node_modules && npm install and trying again?

worked for me
