### ISSUE TITLE
Projects made in 2.0 that contain the text "\b" anywhere in the project are broken.

### ISSUE THREAD

**Issue by GreenScripter** [LLK/scratch-gui#5299] opened 2019-11-15 01:32 UTC
### Expected Behavior
_Projects made in 2.0 that contain the text "\b" anywhere in the code should load and contain "\b" in 3.0 as well_

### Actual Behavior

_The scratch 3.0 editor crashes and fails to load the project._

### Steps to Reproduce

_If you take any block (for example the "say [text]" block) and type the characters "\b" in the text field, save it and upload it to scratch 3.0 the project will fail to load. This appears to work fine with other characters instead of b. Note that this is actually the two different characters "\\" and "b" which in the project.json from the 2.0 project file is encoded as "\\\\b"_ 
Typing "\b" anywhere in a 3.0 project will also make it fail to save.

### Operating System and Browser

_Mac 10.14, modern Chrome_

### This issue actually appears in 3.0 projects as well, I didn't notice until I was editing this.

**Comment by apple502j** [comment] 2019-11-15 03:49
Duplicate of LLK/scratch-www#3497
Duplicate of LLK/scratch-parser#56

**Comment by BryceLTaylor** [comment] 2022-03-03 21:57
Closing as duplicate

**Closed by BryceLTaylor** 2022-03-03 21:57 UTC
