### ISSUE TITLE
scratch 3.0 vectors blur at large sizes

### ISSUE THREAD

**Issue by travisgamemaker** [LLK/scratch-gui#8554] opened 2022-10-03 06:16 UTC
### Expected Behavior

scratch 3.0 vectors should be the same as scratch 2.0 vectors (screenshot of scratch 2.0 desktop provided)

### Actual Behavior

scratch 3.0 vectors are blurrier than scratch 2.0 vectors (screenshot of scratch 3.0 desktop provided)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://scratch.mit.edu/projects/74711180/'
2. Click on the green flag
3. See visual error

### System Details
_If the problem occurs in the browser, please provide operating system and browser e.g. Mac OS 10.11.6 Safari 10.0_

_If using one of the Apps please provide the app version and device details, e.g. Scratch 3.0.57, Android 9 on HP x360 Chromebook_

Scratch 3.29.1, Windows 11 on Lenovo Legion 5 15IMH05H

**Screenshots**
![sb2 scratch vector](https://user-images.githubusercontent.com/81720456/193511777-5b798e98-0094-43f6-b4c9-76ad261da30c.png)

![sb3 scratch vector](https://user-images.githubusercontent.com/81720456/193511792-c66cff04-93f0-45a1-a79d-04dd5fe16477.png)

**Comment by cwillisf** [comment] 2022-10-06 16:13
This appears to be a duplicate of LLK/scratch-render#548. Unfortunately, that's a somewhat unavoidable consequence of a change that we made in order to fix compatibility with certain graphics hardware. Basically, that costume is too big.

The best workaround would be to make smaller costumes. That might mean building the "map" in a game like this out of several sprites, or clones of the same sprite, with multiple different costumes. Another option would be to separate things that need to stay crisp (like text) into a different costume. The large map costume would still be a bit blurry, but it might not negatively affect the project.

**Closed as not planned by cwillisf** 2022-10-06 16:13 UTC
