### ISSUE TITLE
It is urgent to add Arduino extensions to GUI.

### ISSUE THREAD

**Issue by gzeic080** [LLK/scratch-gui#3432] opened 2018-10-19 14:14 UTC
It is urgent to add Arduino extensions to GUI.

**Comment by apple502j** [comment] 2018-10-19 22:29
Duplicate of #1164

**Comment by apple502j** [comment] 2018-10-19 22:29
Duplicate of #1164

**Comment by thisandagain** [comment] 2018-10-23 15:49
Tracking request in https://github.com/LLK/scratch-gui/issues/1164

**Closed by thisandagain** 2018-10-23 15:49 UTC
