### ISSUE TITLE
Stage is too small in normal mode

### ISSUE THREAD

**Issue by tomrow** [LLK/scratch-gui#2413] opened 2018-06-20 15:39 UTC
**What happens:**
Aliased bitmaps on the stage appear blurry due to downscaling, because the regular stage is 2 pixels too small on each axis.
**What is expected to happen:**
Stage should be 480x360 pixels in size.
**Steps to reproduce:**
Load a Scratch 2 project
**Browser Information:**
Chrome on 64-Bit Windows
Edge on 64-Bit Windows
Chromium on Raspberry Pi 3B+

**Comment by paulkaplan** [comment] 2018-06-21 22:53
Interesting, it does seem to be confirmed by the style inspector in chrome/mac

![image](https://user-images.githubusercontent.com/654102/41749147-ed8897d8-7582-11e8-8584-57debf88119d.png)

It looks like [this PR](https://github.com/LLK/scratch-gui/pull/2020) made it so the things within the stage wrapper are forced to `box-sizing: border-box` which puts the border inside the width/height for calculating the size, causing the canvas element itself to be 2px smaller than it is told to be. I'm not familiar with the issues that were addressed in #2020, but the stage very much needs to be `box-sizing: content-box;`. 

This seems like something that would be most easily resolved with a quick convo with @chrisgarrity – I'll follow up with her offline.

**Closed** 2018-06-22 13:04 UTC
Labels: bug, needs-discussion
