### ISSUE TITLE
Can't use scratch desktop on mac os

### ISSUE THREAD

**Issue by shinningstar** [LLK/scratch-gui#5226] opened 2019-10-04 15:30 UTC
### Expected Behavior

To use scratch desktop on Mac OS

### Actual Behavior

Your browser does not support WebGL

### Steps to Reproduce

Install and open Scratch Desktop

### Operating System and Browser

Mac OS 10.12.6 Safari 10.1.2

### Other information
I can open https://llk.github.io/scratch-gui/master/ without any problem. I've check https://webglreport.com and there's no problem with my browser to support WebGL. The browser(Safari) supports both WebGL 1 and WebGL 2 well.

**Comment by apple502j** [comment] 2019-10-04 16:25
Scratch Desktop is supported in macOS 10.**13**+. Not working on older versions is not a bug.

**Comment by maximagit** [comment] 2020-04-28 17:02
Hello,
I got the same issue while running macOS 10.13.6 (17G12034)

Platform: MacIntel
Browser User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Context Name: webgl2
GL Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Shading Language Version: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)

Regards

**Comment by cwillisf** [comment] 2022-04-14 20:57
I'm closing this since we don't currently know of a case where it's still true. Adding support for WebGL 2 in LLK/scratch-render#953 may have resolved this for some users.

Please reopen if you encounter this on a supported computer. If so, please include as much detail as possible about your software and hardware configuration, especially the specific model of Mac. Thanks!

**Closed by cwillisf** 2022-04-14 20:57 UTC
Labels: needs investigation
