### ISSUE TITLE
Fonts on tutorial cards in Windows Chrome/Edge render differently

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2191] opened 2018-05-30 19:47 UTC
### Expected Behavior

Fonts in the 3.0 editors should render the same (or similarly) across browsers and platforms.

### Actual Behavior

In the tutorial cards, the font is a sans serif font on Mac Chrome, but a serif font on Windows Chrome/Edge.

Screenshot from Edge ('see more' button and titles of other tutorial cards):
![image](https://user-images.githubusercontent.com/1786240/40744229-e84f2902-6421-11e8-9fda-a6c2ccfa56b5.png)

**Comment by paulkaplan** [comment] 2018-05-30 20:52
Duplicate of https://github.com/LLK/scratch-gui/issues/1961 I believe, although that was reported on Windows Chrome

**Closed by paulkaplan** 2018-05-30 20:52 UTC
Labels: bug, platforms
