### ISSUE TITLE
Dragged sprite leaves jagged pen trail

### ISSUE THREAD

**Issue by sjhuang26** [LLK/scratch-gui#1127] opened 2017-12-26 12:30 UTC
### Expected Behavior

When a sprite has its pen down and it is dragged, it should leave a smooth pen trail behind it.

### Actual Behavior

The pen trail looks like this:
![image](https://user-images.githubusercontent.com/29558846/34356747-a7356f0e-ea0e-11e7-95d6-901894648671.png)

### Steps to Reproduce

1. Select a sprite.
2. Add the "Pen" extension.
3. Click the "pen down" block.
4. Drag the sprite.

### Operating System and Browser

Chrome 63, Windows 7

**Comment by paulkaplan** [comment] 2017-12-27 16:27
Closing as a duplicate of https://github.com/LLK/scratch-render/issues/144

**Closed by paulkaplan** 2017-12-27 16:27 UTC
