### ISSUE TITLE
Item from list block missing "random" and "last" options.

### ISSUE THREAD

**Issue by martinohanlon** [LLK/scratch-gui#3936] opened 2018-12-04 10:47 UTC
In Scratch 2 you can get either a numbered item, last item, or random item from a list.

The last and random options dont exist in Scratch 3, meaning you have to use the "length of" and "random" blocks to achieve the same.

![scratch get item diff](https://user-images.githubusercontent.com/2329501/49436653-8a845300-f7b1-11e8-8a2e-0c0dc8f0286b.png)

This approach seems to add significant complexity both in terms of block usage and conceptually its quite difficult to understand.

**Comment by apple502j** [comment] 2018-12-04 10:56
Duplicate of LLK/scratch-blocks#1335

**Closed** 2018-12-04 15:20 UTC
