### ISSUE TITLE
Standard scroll bar when block categories exceed view

### ISSUE THREAD

**Issue by FateForWindows** [LLK/scratch-gui#885] opened 2017-11-09 23:39 UTC
### Expected Behavior

There should be at least a slim scroll bar to the right of the different block categories when they exceed the amount horizontal browser space present. Other similar overlapping problems are present.

### Actual Behavior

Standard scroll bar appears at the side, blocking part of the block list. Some 
elements are overlapping others.

### Steps to Reproduce

Shrink the browser window so that the categories do not fill up the entire space.

### Operating System and Browser

Windows 10 10.0.16299 1709, Chrome 62.0.3202.89

![image](https://user-images.githubusercontent.com/14127573/32635222-567368ce-c57d-11e7-93da-738b13bcd1ab.png)

**Comment by VutonDesign** [comment] 2017-11-10 08:06
Duplicate of #755 which is being tracked in LLK/scratch-blocks#1119

**Comment by thisandagain** [comment] 2017-11-10 14:08
Tracking in https://github.com/LLK/scratch-blocks/issues/1119

**Closed by thisandagain** 2017-11-10 14:08 UTC
