### ISSUE TITLE
how to create 8*8 matrix

### ISSUE THREAD

**Issue by crousekimo** [LLK/scratch-gui#6938] opened 2021-03-18 01:45 UTC
I found microbit has a 5*5 matrix blocktype.
May I know how to create 8*8 matrix blocktype?

![image](https://user-images.githubusercontent.com/43980978/111560944-92bffb00-87ce-11eb-9070-7e8e12045681.png)

**Comment by apple502j** [comment] 2021-03-18 06:57
Duplicate of LLK/scratch-vm#2226

**Comment by BryceLTaylor** [comment] 2021-03-18 15:39
Closing as duplicate

**Closed as completed by BryceLTaylor** 2021-03-18 15:39 UTC
