### ISSUE TITLE
Variables disappeared!

### ISSUE THREAD

**Issue by changwcn** [LLK/scratch-gui#4163] opened 2018-12-20 05:27 UTC
### Expected Behavior

Variables maintain display state and position when upload a project from computer.
![1](https://user-images.githubusercontent.com/12888166/50265533-0261a700-045b-11e9-86e3-5dd58a2e22a7.png)

### Actual Behavior

Variables disappeared!
![2](https://user-images.githubusercontent.com/12888166/50265536-068dc480-045b-11e9-8521-0f90eaa3c60e.png)

### Steps to Reproduce

1. Open a project, create a variable, check it;
1. Variable show on the stage;
1. Download to computer (Save);
1. Upload from computer (Open)
1. Variables disappeared!

> Variables can maintain display state and position with Scratch 2.0

### Operating System and Browser
Win 10, Chrome 70

**Comment by joker314** [comment] 2018-12-20 06:51
Posible regression from LLK/scratch-vm#1686 (unless that hasn't been merged into master yet)

**Comment by kchadha** [comment] 2018-12-20 14:31
@changwcn, if you are seeing this issue on https://beta.scratch.mit.edu, it is because the code for saving and loading variable monitors has not landed yet.

I tried reproducing this issue on our latest version of scratch 3.0 https://llk.github.io/scratch-gui/develop/ using the following steps, and did not see the bug you mentioned:

1) In a new project, create a new variable 'foo'
2) The monitor for 'foo' is on by default. I moved the monitor into a new position on the stage.
3) I saved the project to my computer
4) I load the project, the monitor is still there in the correct position

**Closed** 2018-12-20 14:32 UTC
Labels: bug, needs-repro
