### ISSUE TITLE
Hiding a variable monitor closes the soft keyboard (Also in production)

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#5936] opened 2020-06-24 20:06 UTC
From @BryceLTaylor bug hunt 6/23

**Comment by BoomerScratch** [comment] 2020-06-25 12:36
Duplicate of #5755, I think.

**Comment by BryceLTaylor** [comment] 2020-06-25 19:58
Closing as duplicate.

**Closed by BryceLTaylor** 2020-06-25 19:58 UTC
