### ISSUE TITLE
"Costumes" tab is still "Costumes" when I select stage

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1550] opened 2018-03-04 07:46 UTC
### Expected Behavior
Costume tab will be "Backdrop" when I select stage
### Actual Behavior
Still **costume**
![Still costume](https://i.gyazo.com/0a2670bc73499c06269c516b0116be48.png)
### Steps to Reproduce
1. Select stage
### Operating System and Browser
Windows 7 Home Premium 64bit SP1
firefox 58.0.2

**Comment by bartljak** [comment] 2018-03-06 20:39
I'm not sure if changing Costumes to say Backdrops depending on what the user has selected is the best way to implement this. What about adding a fourth tab for backdrops? This way the user always knows where to edit backdrops and costumes without having to select a backdrop or sprite.

**Comment by paulkaplan** [comment] 2018-04-25 16:39
This is a duplicate of https://github.com/LLK/scratch-gui/issues/267, I'm going to close this issue and track it on 267.

**Closed by paulkaplan** 2018-04-25 16:39 UTC
Labels: bug
