### ISSUE TITLE
Monitor  can't change by drop down menu

### ISSUE THREAD

**Issue by felix2ch** [LLK/scratch-gui#818] opened 2017-10-29 14:21 UTC
<img width="144" alt="screen shot 2017-10-29 at 10 14 17 pm" src="https://user-images.githubusercontent.com/6711220/32144622-922f2284-bcf6-11e7-8814-0850741fc85a.png">

### Expected Behavior

Change the item of drop down menu, monitor on stage should change according the item.
Or reset block's check box

### Actual Behavior

Nothing changed

**Comment by paulkaplan** [comment] 2017-10-30 19:30
Closing as a duplicate of https://github.com/LLK/scratch-gui/issues/785.

**Closed by paulkaplan** 2017-10-30 19:30 UTC
