### ISSUE TITLE
Touching mouse pointer is not working in 3.0

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#2590] opened 2018-07-11 18:43 UTC
### Expected Behavior
https://scratch.mit.edu/projects/23875878/#editor

### Actual Behavior
https://preview.scratch.mit.edu/#23875878

### Steps to Reproduce
1. Open 2.0 project in 3.0
2. Notice that the touching mouse pointer block does not work 

### Operating System and Browser
Chrome 67 (macOS High Sierra)

**Comment by techwonder21** [comment] 2018-07-11 18:47
https://drive.google.com/file/d/1Yz0t2CI9I1RxUy_jbm3XnWFZd_LDepdJ/view?usp=sharing

**Comment by Mr-Dave2** [comment] 2018-07-12 04:15
I think this is a duplicate of this issue: Touching mouse pointer" always returns false when the sprite is hidden #284

I see the cat toggle between show and hidden if a wait one second is inserted after the if/then else block.

**Comment by thisandagain** [comment] 2018-07-18 15:12
Tracking in https://github.com/LLK/scratch-render/issues/284

**Closed** 2018-07-18 15:13 UTC
