### ISSUE TITLE
Scratch 1.4 Support

### ISSUE THREAD

**Issue by JuegOStrower** [LLK/scratch-gui#972] opened 2017-11-30 01:03 UTC
When I try to open an Scratch 1.4, it doesn't load. You can try this in [this project](https://scratch.mit.edu/projects/1234) If you download that project json (from [this link](https://cdn.projects.scratch.mit.edu/internalapi/project/1234/get/)), you can check that it was uploaded from the scratch 1.4 editor

**Comment by thisandagain** [comment] 2017-11-30 15:24
Yup! We haven't built out support for importing Scratch 1.4 projects yet. We plan to do this next year.

**Comment by rschamp** [comment] 2018-02-22 15:08
Dupe of https://github.com/LLK/scratch-vm/issues/128

**Closed by rschamp** 2018-02-22 15:08 UTC
Labels: feature
