### ISSUE TITLE
Flappy Bird crashes paint editor

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2801] opened 2018-08-06 19:19 UTC
### Expected Behavior

If you open this project: https://llk.github.io/scratch-gui/develop/#18262469
Select Sprite4 and open the paint editor you should be able to see the paint editor.

### Actual Behavior

![screen shot 2018-08-06 at 3 10 38 pm](https://user-images.githubusercontent.com/1088291/43736245-ec752b3c-998a-11e8-8f7d-bd1ac3e6fe87.png)

### Steps to Reproduce

Open the project above
Select Sprite 4
Select the Costumes Tab
Note: There is an error in the console and the paint editor does not appear, instead an oops message appears.

### Operating System and Browser

Chrome on Mac

**Comment by paulkaplan** [comment] 2018-08-06 19:25
Duplicate of https://github.com/LLK/paper.js/issues/13

**Closed by paulkaplan** 2018-08-06 19:25 UTC
Labels: bug
