### ISSUE TITLE
Not registering clicks on sprite.

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#1061] opened 2017-12-18 14:50 UTC
### Expected Behavior
You should be able to click and drag a sprite in the stage to move it to a desired location on a stage. When using the this sprite clicked event, click on the sprite should execute the blocks.

### Actual Behavior
An attempt to drag or click on the sprite results in a 
"Uncaught TypeError: Cannot read property 'rotationCenter' of null" printed to the console. The sprite doesn't move."

### Steps to Reproduce
1. go to costumes tab
2. make your own sprite using the sprite editor.
3. change back to the blocks tab and try to drag sprite. 
4. click on the code block to see it execute...compare that to clicking on the sprite itself.
5. clicking on the sprite also doesn't update the selected sprite

### Operating System and Browser

Mac OS 10.12 Chrome 62.0.3202.94

---
Moved from LLK/scratch-render#218
/cc @quachtina96

**Comment by paulkaplan** [comment] 2017-12-18 15:45
@quachtina96 I cannot seem to reproduce this. Could you try to give more explicit steps (exactly what blocks/stacks to make, exactly how you created your own costume, etc?)

**Comment by paulkaplan** [comment] 2018-07-24 20:56
Closing due to lack of repro

**Closed by paulkaplan** 2018-07-24 20:56 UTC
Labels: needs-repro
