### ISSUE TITLE
Ctrl + Green Flag should mute the project

### ISSUE THREAD

**Issue by joker314** [LLK/scratch-gui#2863] opened 2018-08-14 13:32 UTC
### Expected Behavior

In Scratch 2.0, `ctrl`-clicking the green flag (in a similar way to how `shift`-clicking enabled turbo mode) would disable audio (until the green flag is clicked without `ctrl`)

This means if you're in a public place, you don't fill the room with unwanted noise.

Also, two feature requests about this:
- In 2.0, enabling turbo mode in muted mode would disable muted mode -- this seems unintuitive
- In 2.0, enabling muted mode restarted the project (unlike turbo mode) -- this seems annoying if you're half-way through a project
### Actual Behavior

In Scratch 3.0, `ctrl`-clicking the green flag still allows audio to be played.

### Steps to Reproduce

1. Visit a project that plays audio in 2.0, e.g., [12199089](https://scratch.mit.edu/projects/12199089/)
2. Start the project and observe audio
3. Ctrl + Click the green flag
4. Observe a lack of audio
5. Repeat steps 1 -- 3 with the same project in 3.0, e.g. [12199089](https://beta.scratch.mit.edu/#12199089) and observe the audio **still plays**

Note: sounds should be muted until the green flag is pressed without `ctrl`, not just in green flag scripts.

### Operating System and Browser

Windows 10 Chrome v68.0.3440.106

**Comment by ScratchDiogoh** [comment] 2018-08-14 14:49
Hi, I think it's not **exactly** a bug, but thanks for reporting the problem!
I think this shortcut `ctrl + green flag` is not yet enabled

**Comment by rschamp** [comment] 2018-08-14 14:59
Thanks @joker314 — this is a dupe of #1028

**Closed by rschamp** 2018-08-14 14:59 UTC
