### ISSUE TITLE
Feature request: show sound length in sound library

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2474] opened 2018-06-26 16:19 UTC
### Expected Behavior
It would be nice to see the sound length in the library

### Actual Behavior
When you hover over sounds to discover them, it's easy to not realize how long sounds are and miss most of the sound

**Comment by paulkaplan** [comment] 2019-08-02 14:28
Closing as a duplicate of https://github.com/LLK/scratch-gui/issues/1962

**Closed by paulkaplan** 2019-08-02 14:28 UTC
Labels: feature, request
