### ISSUE TITLE
Uploading a project always creates a new project

### ISSUE THREAD

**Issue by arnohuetter** [LLK/scratch-gui#4249] opened 2019-01-04 07:59 UTC
### Expected Behavior

In Scratch 2.0 it was possible to upload stored projects into existing ones. Very helpful for coding and testing work, as intermediate or premature code changes in a shared project would otherwise affect Scratchers currently running it. It's common practice, esp. for popular projects, to do all dev work in a project copy, then upload it back into the original project when done. Also this would allow to revert changes much more easily.

### Actual Behavior

Uploading a project creates a new project in Scratch 3.0.

### Steps to Reproduce

File / Load from your computer / choose any project (either sb2 or sb3 format) in Scratch 3.0

### Operating System and Browser

Windows 10, Chrome 71.0.3578.98

**Comment by towerofnix** [comment] 2019-01-06 05:37
Duplicate of #4119 - there's some discussion there about how to make this better.

**Comment by thisandagain** [comment] 2019-01-07 14:05
Tracking in https://github.com/LLK/scratch-gui/issues/4119

**Closed by thisandagain** 2019-01-07 14:05 UTC
