### ISSUE TITLE
Can't delete all sprites

### ISSUE THREAD

**Issue by sjhuang26** [LLK/scratch-gui#948] opened 2017-11-25 14:05 UTC
### Expected Behavior

When a project contains a single sprite and that sprite is deleted (leaving a project with no sprites), the editor should allow this.

### Actual Behavior

The editor crashes once all the sprites are deleted, and three errors appear in the console.

### Steps to Reproduce

Delete all the sprites in a project.

### Operating System and Browser

Chrome 62 on Windows 7

**Comment by Kenny2github** [comment] 2017-11-25 14:22
Can repro on Chrome 62 on Windows 10. Here's a screenshot of my errors:
![image](https://user-images.githubusercontent.com/28599280/33231349-fdac5656-d22e-11e7-8b20-f1aeeec858d4.png)
a screenshot of the editor is not needed - it simply turns completely blank.

**This is a regression**. Deleting the last sprite works on master, but not on develop.

**Comment by sjhuang26** [comment] 2017-11-25 19:05
Note that the crash only occurs if the sprite is selected when it is deleted -- not if the stage is selected when the last sprite is deleted.

**Comment by sjhuang26** [comment] 2017-11-26 13:13
Clarification:

Doesn't crash if you delete the sprite like this:
![image](https://user-images.githubusercontent.com/29558846/33240255-5fdfe584-d281-11e7-982a-a36fda1f3ad1.png)

Does crash if you click the "x" and delete the sprite like this:
![image](https://user-images.githubusercontent.com/29558846/33240260-763ab4b2-d281-11e7-9fde-c0c9c63585da.png)

**Comment by dalearn** [comment] 2017-11-27 17:23
Hmmm, that's interesting because it doesn't appear to do it on Safari 11.

**Comment by redmangospros** [comment] 2017-11-27 21:14
@dalearn saafari does not work good with scratch gui!

**Comment by VutonDesign** [comment] 2017-11-27 22:14
@redmangospros What doesn't work for you? Most of scratch-gui seems to work as normal on safari. (Apart from this particular bug, which also happens to be a problem on Chrome 62 too.)

**Comment by redmangospros** [comment] 2017-11-27 23:00
Sorry, I meant Internet explorer and IE Edge.

**Comment by VutonDesign** [comment] 2017-11-28 08:07
@redmangospros Can you stop deleting your messages? It makes this conversation string really confusing.

**Comment by thisandagain** [comment] 2017-11-28 13:10
Thanks for all the details @sjhuang26 !

**Comment by paulkaplan** [comment] 2017-12-01 14:54
Fixed by https://github.com/LLK/scratch-gui/pull/978

**Closed by paulkaplan** 2017-12-01 14:54 UTC
Labels: bug, help wanted
