### ISSUE TITLE
"Define" feature missing

### ISSUE THREAD

**Issue by DrDingleberry** [LLK/scratch-gui#4273] opened 2019-01-06 04:56 UTC
### Expected Behavior
Right-clicking on a custom block in the code side-bar brings up a context menu. There should be two options, "edit..." and "define". The "define" option would take the user to the point in the project where that custom block was defined at.
### Actual Behavior

The only option that appears is the "edit..." option.

### Steps to Reproduce

Right-click on a custom block in the code-sidebar.

### Operating System and Browser

Firefox 64.0 (64 bit) Windows 10

**Comment by towerofnix** [comment] 2019-01-06 05:16
Duplicate of LLK/scratch-blocks#1136, which has a to-be-reviewed PR that implements this: LLK/scratch-blocks#1834.

**Comment by DrDingleberry** [comment] 2019-01-06 05:17
Ah. Good to hear!

**Comment by thisandagain** [comment] 2019-01-06 13:18
Tracking in LLK/scratch-blocks#1136

**Closed by thisandagain** 2019-01-06 13:18 UTC
