### ISSUE TITLE
Can't release copied blocks on Android phones

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2376] opened 2018-06-18 00:01 UTC
### Expected Behavior

I can release them

### Actual Behavior

nope

### Steps to Reproduce

Copy blocks on Android phones

### Operating System and Browser

MI PAD 4.4.4, CHROME

**Comment by picklesrus** [comment] 2018-10-04 14:28
Closing this a duplicate of https://github.com/LLK/scratch-blocks/issues/1647

**Closed by picklesrus** 2018-10-04 14:28 UTC
Labels: android, bug, needs-triage, touch
