### ISSUE TITLE
Feature improvement

### ISSUE THREAD

**Issue by cross-hello** [LLK/scratch-gui#5681] opened 2020-04-25 09:37 UTC
### Expected Behavior

The carven stage should have more bigger. Morr room will be appreciate~

### Actual Behavior

Draw with a small sizes.
![image](https://user-images.githubusercontent.com/42733664/80276385-02427d00-871b-11ea-9e13-1e5c6bacd34c.png)

### Steps to Reproduce

- Open Scratch
- Click Costumes
- You could see the drawing carvens.

### Operating System and Browser

Win7-64bit with Scratch Desktop 3.9.0 version.

**Comment by adroitwhiz** [comment] 2020-04-26 00:23
This is a duplicate of https://github.com/LLK/scratch-paint/issues/965, and that feature is currently being implemented in https://github.com/LLK/scratch-paint/pull/975.

**Comment by cross-hello** [comment] 2020-04-26 10:54
I am so expecting~

**Closed** 2020-04-27 18:33 UTC
