### ISSUE TITLE
Sprites load in a different order in 3.0

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2633] opened 2018-07-15 04:36 UTC
### Expected Behavior
Sprites are in the same order in 2.0 and 3.0 project

### Actual Behavior
The sprites may be in a different order

### Steps to Reproduce
See https://scratch.mit.edu/projects/144885018/#editor
vs https://llk.github.io/scratch-gui/develop/#144885018
In 2.0 the sprites are in order Thumbnail, Moana art, Reference, Trail
In 3.0 the sprites are in order Reference, Moana art, Trail, Thumbnail

In 3.0 Reference is selected by default, which is a hidden sprite. In 2.0 Thumbnail is selected by default. The creator seems to expect thumbnail to be selected by default, since there's a comment in the blocks editor there telling viewers not to steal art.

### Operating System and Browser
Mac Chrome

**Comment by towerofnix** [comment] 2018-07-15 21:04
Probably a duplicate of #939.

**Comment by thisandagain** [comment] 2018-07-18 15:01
Tracking in https://github.com/LLK/scratch-gui/issues/939

**Closed by thisandagain** 2018-07-18 15:01 UTC
