### ISSUE TITLE
Variable status changes by double-rightclicking 

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#3863] opened 2018-11-24 09:09 UTC
### Expected Behavior
The status should not change when we double-right-click the variable. 

### Actual Behavior

It changes when double-right-clicking the monitor.

### Steps to Reproduce
Double-right-click the monitor

### Operating System and Browser
Windows 7, Firefox 63

**Comment by epicfaace** [comment] 2018-12-12 01:20
What do you mean by "variable status"?

**Comment by joker314** [comment] 2018-12-12 01:46
@towerofnix I believe the core of the issue is "double _right_ click"

**Comment by towerofnix** [comment] 2018-12-12 02:00
@joker314 Ohhhh right, of course! I missed that, oops. There would need to be a separate function inside `onDoubleClick` which checks that the button clicked is left-click (or maybe [the `onNextMode`](https://github.com/LLK/scratch-gui/blob/61c02651b1d1e4684e919a1e2f0c00e99890c4e4/src/containers/monitor.jsx#L97) could just take an `event` value and, if present, check that itself).

Aside: This is a duplicate of #2089.

**Comment by BryceLTaylor** [comment] 2020-06-16 15:43
Closing as duplicate

**Closed by BryceLTaylor** 2020-06-16 15:43 UTC
Labels: bug, help wanted
