### ISSUE TITLE
Variable in blocks are not being translated

### ISSUE THREAD

**Issue by sobreira** [LLK/scratch-gui#5489] opened 2020-02-29 11:20 UTC
### Expected Behavior
Is expected to have some blocks translated to the selected languages - blocks itself is ok, but variable inside each blocks are not following same logic.

### Actual Behavior
Some blocks are not being translated properly. After language selection keeps with original/default language - english

### Steps to Reproduce
1st -
*Set your Chrome/Firefox to other language like Brazilian Portuguese or Spanish.
*Go to https://scratch.mit.edu/projects/editor/
*Check if menu is translated
*Go to Sensores, in case of pt-br or esp (equivalent of Sensing)
You should see something like:
![image](https://user-images.githubusercontent.com/5200448/75606083-0b6eef00-5ac8-11ea-90f9-27c0fc7f6425.png)

2nd-
*Set your Chrome/Firefox to your original language - even english.
*Go to https://scratch.mit.edu/projects/editor/
*Check if menu is translated
*Don´t open the Sensing Menu
*Change the language to to Brazilian Portuguese or Spanish or anyone you want to test
*Go to Sensores, in case of pt-br or esp (equivalent of Sensing)
You should see something like:
![image](https://user-images.githubusercontent.com/5200448/75606141-99e37080-5ac8-11ea-9257-7156d773e31f.png)

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
This issue are happening with the following block keys:
`SENSING_ASK_TEXT` : 
`ScratchBlocks.ScratchMsgs.translate('SENSING_ASK_TEXT', 'What\'s your name?');`
`OPERATORS_JOIN_APPLE` :
` ScratchBlocks.ScratchMsgs.translate('OPERATORS_JOIN_APPLE', 'apple');`
`OPERATORS_JOIN_BANANA` : 
`ScratchBlocks.ScratchMsgs.translate('OPERATORS_JOIN_BANANA', 'banana');`
`OPERATORS_LETTEROF_APPLE` :
`ScratchBlocks.ScratchMsgs.translate('OPERATORS_LETTEROF_APPLE', 'a');`

### Operating System and Browser
Windows 10

**Comment by apple502j** [comment] 2020-02-29 11:32
Duplicate of #5445

**Comment by BryceLTaylor** [comment] 2020-03-03 16:50
Tracking in #5445

**Closed by BryceLTaylor** 2020-03-03 16:50 UTC
