### ISSUE TITLE
Right-click delete of custom definitions will keep the block in the menu

### ISSUE THREAD

**Issue by amazinigmech2418** [LLK/scratch-gui#1358] opened 2018-01-27 23:15 UTC
### Expected Behavior

When you right-click and delete the definition, it should remove the custom block.

### Actual Behavior

The block stays in the menu until you make a new custom block.

### Steps to Reproduce

1. Make a custom block.
2. Right-click the definition.
3. Click delete.
4. See the block still in the menu.

### Operating System and Browser

OS: Windows 10
Browser: Chrome

**Comment by amazinigmech2418** [comment] 2018-01-28 18:12
@thisandagain

**Comment by Kenny2github** [comment] 2018-01-29 04:27
Possible duplicate of #1261 ?

**Comment by paulkaplan** [comment] 2018-01-29 14:41
Are you testing on the develop build (https://llk.github.io/scratch-gui/develop/)? I can't repro on develop  (mac + chrome).

![deleting-custom-blocks](https://user-images.githubusercontent.com/654102/35515977-87a78d90-04d8-11e8-9c47-6e94aa6f9cdf.gif)

**Comment by ktrvs** [comment] 2018-01-29 15:35
@paulkaplan I tested this, and could repro on the master build but not the develop build. So unless it's OS specific (which I doubt it would be), it's probably just a master issue.

**Comment by kchadha** [comment] 2018-01-29 15:45
This is a duplicate of #1261. When I filed that issue, I was definitely referring to the context menu deletion option. This issue should have been fixed by https://github.com/LLK/scratch-blocks/pull/1355.

**Closed** 2018-01-29 17:47 UTC
Labels: needs-repro
