### ISSUE TITLE
Backdrop tile can shrink vertically

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3383] opened 2018-10-15 20:58 UTC
### Expected Behavior

The tile showing the stage thumbnail in the sprite area should have consistent dimensions.

### Actual Behavior

If you draw a wide thin backdrop the tile will shrink down:
![screen shot 2018-10-15 at 4 54 50 pm](https://user-images.githubusercontent.com/1088291/46977897-5a66e080-d09b-11e8-8bca-ae71969f50c6.png)
![screen shot 2018-10-15 at 4 53 25 pm](https://user-images.githubusercontent.com/1088291/46977900-5d61d100-d09b-11e8-9b22-4833d472b9be.png)

### Steps to Reproduce

Create a new project
Paint a new backdrop
Draw a wide thin line across the screen
Note: the tile in the sprite area is the same width but is now much shorter

### Operating System and Browser

Chrome on Mac

**Comment by MasterOfTheTiger** [comment] 2018-10-15 21:06
I was able to reproduce this on Firefox on Android with both Vector and Bitmap.

**Comment by MasterOfTheTiger** [comment] 2018-10-15 21:07
Where is the CSS for this?

**Comment by benjiwheeler** [comment] 2018-10-16 13:00
Closing as duplicate of https://github.com/LLK/scratch-gui/issues/2986

**Closed by benjiwheeler** 2018-10-16 13:00 UTC
Labels: bug
