### ISSUE TITLE
When adding blocks to sprite from backpack, blocks do not initially appear

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#6119] opened 2020-08-24 13:34 UTC
### Expected Behavior

1. select a sprite
1. drag a stack of blocks from the backpack to the sprite tile (not the workspace)

Expected:
3. the stack of blocks appears in the current sprite

### Actual Behavior

3. the stack of blocks does NOT appear in the current sprite
4. you can get them to appear by selecting another sprite, then re-selecting the original sprite

![Aug-24-2020 09-30-49](https://user-images.githubusercontent.com/3431616/91050436-a286b080-e5ec-11ea-9d86-2080b2700ad7.gif)

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment] 2020-08-24 14:06
Duplicate of https://github.com/LLK/scratch-gui/issues/5802

**Closed as completed by BryceLTaylor** 2020-08-24 14:06 UTC
