### ISSUE TITLE
Scratch GUI link not working

### ISSUE THREAD

**Issue by biggiecheesetherat** [LLK/scratch-gui#9448] opened 2024-01-08 01:32 UTC
### Expected Behavior

https://llk.github.io/scratch-gui/develop should open the Scratch GUI.

### Actual Behavior

It opens the Github Pages 404 page.

### Steps to Reproduce

1. Go to 'https://llk.github.io/scratch-gui/develop'
2. See error

### Fix

Replace the URL with https://scratchfoundation.github.io/scratch-gui/.

### System Details
Opera GX (Or just Opera) on Windows 11. 

**Screenshots**
![image](https://github.com/scratchfoundation/scratch-gui/assets/143027785/e4ae8fd6-2531-479b-abb7-ad53ffda08bb)

**Comment by dumorando** [comment] 2024-01-22 18:49
because its the wrong url :trollface:

**Comment by biggiecheesetherat** [comment] 2024-02-07 07:33
i know that

**Comment by tutacat** [comment] 2024-02-19 20:30
Duplicate of #9030

**Comment by cwillisf** [comment] 2024-02-20 15:29
Thanks! Fixed.

**Closed as completed by cwillisf** 2024-02-20 15:29 UTC
