### ISSUE TITLE
Blocks disappear when green flag is clicked and reappear when stopped

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1314] opened 2018-01-21 13:46 UTC
### Expected Behavior
Blocks should not disappear while running

### Actual Behavior
Blocks disappear while running 

### Steps to Reproduce
Add:
When flag is clicked
Forever
Move 10 steps
If touching edge next costume
If on edge bounce

### Operating System and Browser
iPad Pro iOS 11 Chrome 63

**Comment by msintov** [comment] 2018-01-21 15:07
Might be a duplicate of https://github.com/LLK/scratch-blocks/issues/1188?

**Comment by thisandagain** [comment] 2018-01-21 17:36
@msintov Agreed. Tracking in LLK/scratch-blocks#1188

**Closed by thisandagain** 2018-01-21 17:36 UTC
