### ISSUE TITLE
Creating custom block starting with % causes block stack error

### ISSUE THREAD

**Issue by owenkaplinsky** [LLK/scratch-gui#9562] opened 2024-04-13 04:21 UTC
### Expected Behavior

Making a custom block with %anything causes a block stack error

### Actual Behavior

Making a custom block with %anything should cause no errors

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Create a new project
2. Make a new block with the label %anything
3. Click “Ok”
4. Click “Cancel”
5. Click on any section

### System Details
All

**Screenshots**
![image](https://github.com/scratchfoundation/scratch-gui/assets/138824486/4e69fb09-3650-4968-99a6-8c95730b9891)

**Comment by bruh-9000** [comment] 2024-04-13 05:47
Should starting custom blocks with % be disabled, or is there a workaround to allow for users to do it, such as through escaping the character?

**Comment by alexcui03** [comment] 2024-08-06 20:36
Duplicate of scratchfoundation/scratch-blocks#1368

**Closed as not planned** 2024-08-22 18:06 UTC
