### ISSUE TITLE
having a problem when get start

### ISSUE THREAD

**Issue by wojiaofengzhongzhuifeng** [LLK/scratch-gui#4705] opened 2019-04-01 06:08 UTC
### Expected Behavior
show me project without problem
### Actual Behavior

there is something wrong when i get start this project 
### Steps to Reproduce
i use this command to get start 
```
git clone https://github.com/LLK/scratch-gui.git
cd scratch-gui
yarn 
```
then i choice this release version
![image](https://user-images.githubusercontent.com/25478678/55306808-09e81180-5488-11e9-887a-cbd4cd6b9d2f.png)
```
yarn start 
```
console tag show 
![image](https://user-images.githubusercontent.com/25478678/55306892-559abb00-5488-11e9-80d2-1efe237e1780.png)

### Operating System and Browser

Mac OS 10.11.6 Safari 10.0_

@rwaldron @tmickel @boazsender @leoburd  

think you for reading

**Comment by benjiwheeler** [comment] 2019-04-01 13:13
I'm not sure what the problem is, but for starters, you might want to double check that you're following all the steps in the README. I'm not sure what the current state of the overlap is between `yarn` and `npm`. Could you follow the README's steps, and show what happens then?

**Comment by wojiaofengzhongzhuifeng** [comment] 2019-04-01 13:47
@benjiwheeler  i have solve this problem.
i come from China, there is something difference. just do
1️⃣use origin npm mirror, do not use taobao npm mirror
2️⃣use npm instead of yarn
in a word, think you to help me

**Comment by benjiwheeler** [comment] 2019-04-01 13:55
Great! You're welcome! I'll close this issue.

**Closed by benjiwheeler** 2019-04-01 13:55 UTC
