### ISSUE TITLE
Dragging scripts into the bottom left-most sprite of a project with many sprites is almost impossible

### ISSUE THREAD

**Issue by tomrow** [LLK/scratch-gui#6494] opened 2020-12-17 22:53 UTC
### Expected Behavior

Scripts should be able to be dragged to sprites in the bottom left corner of the sprite list with no issues.

### Actual Behavior

The sprite list rapidly alternates between multiple different shapes and it is almost impossible to drag scripts into the bottom left sprite.
[clip0008_x264.zip](https://github.com/LLK/scratch-gui/files/5712542/clip0008_x264.zip)
The video here is zoomed out but it still occurs when zoom is set to 100%.
### Steps to Reproduce
Create a project with 42 sprites, make a script and attempt to drag it into the bottom left -most sprite from the list.
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

![image](https://user-images.githubusercontent.com/10169982/102553415-b635b580-40ba-11eb-9c75-7599905cc39a.png)

**Comment by Kouzeru** [comment] 2021-01-02 03:27
This is a near serious issue, and there is no **copy and paste block** in vanilla Scratch to get around this.
![62JoBYilwi](https://user-images.githubusercontent.com/46141631/103450159-3e3bd200-4ced-11eb-893b-27d897c94f54.gif)

**Comment by apple502j** [comment] 2021-05-03 21:13
Duplicate of #5471

**Comment by benjiwheeler** [comment] 2022-12-06 15:49
Closing this in favor of #5471

**Closed as completed by benjiwheeler** 2022-12-06 15:49 UTC
Labels: priority 2, High Severity, Medium Impact
