### ISSUE TITLE
After adding pen extension, rendering results are different

### ISSUE THREAD

**Issue by Ryuurock** [LLK/scratch-gui#5673] opened 2020-04-23 03:35 UTC
### Expected Behavior

Adding pen extensions should not affect rendering results

### Actual Behavior

Rendering results are affected after adding pen extension

### Steps to Reproduce

1. Load the provided sb3 file
2. Click the green flag
3. The face on the left will move up
4. Add pen extension
5. Reload the provided sb3 file，Click the green flag
6. The face on the left will not move up

### Operating System and Browser

_e.g. Mac OS 10.15.6 Chrome 80.0.3987.163

[jump.zip](https://github.com/LLK/scratch-gui/files/4520095/jump.zip)
**Please modify the file suffix to .sb3**

Below is the animation I recorded
👇before load pen extension
![Apr-23-2020 11-38-09](https://user-images.githubusercontent.com/25604544/80056533-0cb41980-8557-11ea-8831-ee965889d72c.gif)

👇after load pen extension
![Apr-23-2020 11-37-06](https://user-images.githubusercontent.com/25604544/80056554-19d10880-8557-11ea-9a86-5b0a4f78c276.gif)

**Comment by Ryuurock** [comment] 2020-04-23 03:44
After investigation, it is found that it may be the problem caused here
[scratch-vm/src/extensions/scratch3_pen/index.js](https://github.com/LLK/scratch-vm/blob/develop/src/extensions/scratch3_pen/index.js#L70)

**Comment by BryceLTaylor** [comment] 2020-04-27 20:44
@ryuurock I'm unable to reproduce this issue with that project.  Are there more steps you take while adding the pen extension, such as adding any blocks to the project?  Can you cause this issue to happen on a simpler project?

**Comment by Ryuurock** [comment] 2020-04-28 14:31
@BryceLTaylor Ok，I made some fixes

1. Load the provided sb3 file, Click the green flag
2. Check the stage, The face on the left will move up

**Then reload scratch.**
1. First, add pen extension
2. Load the provided sb3 file，Click the green flag
7. The face on the left will not move up

**Comment by BryceLTaylor** [comment] 2020-04-28 14:59
Okay, so to see it you have to load it by doing File>Load from your computer, not reloading the page.  It also seems to only happen with the pen extension (that I've tested so far.). It did not happen with the Music or the Makey Makey extension.

@Ryuurock Can you make a simplified version of the project that has only the minimum number of sprites and scripts to see this issue?  I'd like to get some repro steps for how to create a project that exhibits this issue.

**Comment by Ryuurock** [comment] 2020-04-29 10:12
[simplified_version.zip](https://github.com/LLK/scratch-gui/files/4551050/simplified_version.zip)
@BryceLTaylor simplified version

**Comment by BryceLTaylor** [comment] 2020-05-05 19:35
@Ryuurock thanks!  That's super helpful.

**Comment by adroitwhiz** [comment] 2020-05-07 14:07
This looks like it has something to do with https://github.com/LLK/scratch-render/issues/488. The sprite is testing whether it's touching the color black, but the transparent backdrop seems to be confusing it. If I test this on my "touching white fixes" branch, it works properly.

**Comment by cwillisf** [comment] 2020-08-18 22:27
Current status: we hope this will be fixed by LLK/scratch-render#676, which is still in progress

**Comment by cwillisf** [comment] 2020-09-22 21:09
This appears to be fixed now, probably by LLK/scratch-render#686

**Closed by cwillisf** 2020-09-22 21:09 UTC
Labels: bug, priority 2
