### ISSUE TITLE
SBFileUploader cant upload files in Scratch Desktop

### ISSUE THREAD

**Issue by huaerzx** [LLK/scratch-gui#5284] opened 2019-11-05 11:16 UTC
I got the same problem when i used Scratch Desktop  or  cefsharp for winform.  The scratch cant load any files When the SBFileUploader's props loadingState="LOADING_VM_FILE_UPLOAD"  
![cap_20191105191259](https://user-images.githubusercontent.com/17899585/68203399-a9621980-0000-11ea-9cc8-b63123c882ae.png)

**Comment by apple502j** [comment] 2019-11-25 06:35
Duplicate of #3365

**Comment by carljbowman** [comment] 2022-03-10 22:01
Tracking in https://github.com/LLK/scratch-gui/issues/3365

**Closed by carljbowman** 2022-03-10 22:01 UTC
