### ISSUE TITLE
This project crashes when you see inside

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#6809] opened 2021-02-24 16:34 UTC
### Expected Behavior

Projects don't crash

### Actual Behavior

If you go to [this project](https://scratch.mit.edu/projects/419852226/) and click see inside it will become unresponsive and eventually the tab will crash.  It does not present an error boundary (Blue Screen of Death), the browser tab itself crashes.

### Steps to Reproduce

We need steps to reproduce this issue.  I have downloaded the project.json but I haven't had much time to 

The version saved on January 18, 2021, 07:30:31 (UTC-05:00) works just fine 
[419852226From0730.json.zip](https://github.com/LLK/scratch-gui/files/6037208/419852226From0730.json.zip)
And the next version from January 18, 2021, 07:33:04 (UTC-05:00) does not work
[419852226From0733.json.zip](https://github.com/LLK/scratch-gui/files/6037222/419852226From0733.json.zip)

I have started doing a diff between the two versions, but the project is complex and it will take some more time to figure out.

### Operating System and Browser

Mac Chrome, but it is reported that this happens on multiple browsers.

**Comment by BryceLTaylor** [comment] 2021-02-24 17:10
The bug is definitely a result of adding the "Broadcast [Clone]" block to the "When I start as a clone" stack in the "Menu" sprite.  More investigation is needed.

**Comment by BryceLTaylor** [comment] 2021-02-24 21:55
I created this (relatively) minimal repro project: https://scratch.mit.edu/projects/492574298/editor/. Attach the "broadcast clone" block to the "when I start as a clone" block and click the green flag to crash your tab.

**Comment by apple502j** [comment] 2021-02-25 01:41
Duplicate of LLK/scratch-vm#2282

**Closed as completed** 2021-02-25 15:00 UTC
Labels: needs repro
