### ISSUE TITLE
Comment position and "Save Now" issues

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#5948] opened 2020-06-29 11:19 UTC
### Expected Behavior

Comments stay were you last saved them and the editor does not say "Save Now" upon loading up.

### Actual Behavior

As soon as your project contains a comment **attached to a block**, and you reload the project after saving, it will always say "Save Now" straight away.

Also the position of the comment blocks are not persisted when you move them by dragging their parent block around. They only save if you move the actual comment by hand.

### Steps to Reproduce

Create a new project add a block
Right click block and add a comment
Drag block (not comment) to somewhere else on the screen
save project

reload project and comment will appear back where it was first created, not relative to new block position.
Also, 'Save Now' wording will have appeared on menu bar.

### Operating System and Browser

Windows 10, chrome.

**Comment by apple502j** [comment] 2020-06-29 12:47
Duplicate of #4776 which is duplicate of  LLK/scratch-blocks#1566

**Comment by griffpatch** [comment] 2020-06-29 14:01
Comments have not saved their locations for over 2 years! Lol - no wonder
no one comments their code any longer in scratch... That's a shame.
Deserves a fix I think!

**Comment by griffpatch** [comment] 2020-06-29 15:09
Has it also been reported that comments simply disappear if you switch to
costume tab and back to code editor a few times?

**Comment by apple502j** [comment] 2020-06-29 15:39
List of Issues with Comments:
- #5638 - A bug with costume tab is described there, but no repro.
- #4776 - Issues with moving blocks with comments
- #3687 - Duplicated sprites lose comments. Gonna check if I can still repro
- #2299 - Block comments appear after floating comments
- LLK/scratch-vm#2027 - Projects save without changes when block comment is loaded
- LLK/scratch-vm#2026 - Projects don't save when block comment is edited (before un-focusing
- LLK/scratch-vm#1893 - Comments attached to variable blocks disappear after re-load
- LLK/scratch-vm#1499 - Issues with deserializing sb2 with comments attached to custom blocks
- LLK/scratch-vm#1257 - Crash with deserializing sb2 with multiple comments attached to a single block
- LLK/scratch-blocks#1973 - Undo can remove block comments from blocks just after opening
- LLK/scratch-blocks#1936 - Undoing removing blocks with comments attached do not restore comments
- LLK/scratch-blocks#1705 - Issues with deserializing sb2 with comments
- LLK/scratch-sb1-converter#3 - Issues with deserializing sb with non-block comments
- LLK/scratch-sb1-converter#36 - Crash with deserializing sb with comments

**Comment by apple502j** [comment] 2020-06-30 02:58
Note: #2299 is probably causing LLK/scratch-vm#2027 and LLK/scratch-blocks#1973

**Comment by Explosion-Scratch** [comment] 2020-07-02 17:49
@griffpatch  I can reproduce the comment disappearance. Mac 10.13.6 Safari.

**Comment by BryceLTaylor** [comment] 2020-07-09 20:40
Closing as duplicate of https://github.com/LLK/scratch-blocks/issues/1566

**Closed by BryceLTaylor** 2020-07-09 20:40 UTC
