### ISSUE TITLE
Hidden sprites don't stamp (they do in 2.0)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#188] opened 2017-03-06 15:15 UTC
Reported via internal playtest 3/3/17.

### Expected Behavior

A hidden sprite should stamp, as it does in 2.0, unless we intentionally want to change that behaviour in 3.0?

### Actual Behavior

A hidden sprite doesn't stamp, while it does in 2.0 (e.g. Project ID 77009574).

### Steps to Reproduce

Use Project ID 77009574 to view the behaviour.

### Operating System and Browser

_Mac & Chrome_

**Comment by liam4** [comment] 2017-03-06 15:38
Duplicate of https://github.com/LLK/scratch-vm/issues/425, I believe.

**Comment by thisandagain** [comment] 2017-03-06 18:28
Moved to LLK/scratch-vm#492

**Closed by thisandagain** 2017-03-06 18:28 UTC
