### ISSUE TITLE
variable changes much faster than the asset moves

### ISSUE THREAD

**Issue by aoloe** [LLK/scratch-gui#4450] opened 2019-01-29 09:30 UTC
### Expected Behavior

"change y by dy" should be called once in each frame and the ball should fly with a nice trajectory (with dy sinking slowly)

### Actual Behavior

dy sinks all at once and, after some time, starts to sink slowly.

### Steps to Reproduce

![bug-dy](https://user-images.githubusercontent.com/1857016/51897710-a53d0780-23af-11e9-8d64-38c652a51564.png)

adding a very small `wait 0.001 seconds` solves the issue.
![bug-dy-sleep](https://user-images.githubusercontent.com/1857016/51897905-0c5abc00-23b0-11e9-8637-ef63932a1727.png)

![bug-dy](https://user-images.githubusercontent.com/1857016/51898227-c2bea100-23b0-11e9-9d6f-2373df11b55a.gif)

### Operating System and Browser

_Linux  + Chromium_

**Comment by aoloe** [comment] 2019-01-29 09:51
slightly different project: this works!

![bug-dy-works](https://user-images.githubusercontent.com/1857016/51899662-cdc70080-23b3-11e9-85fd-b67cd0bdd6cb.gif)

**Comment by aoloe** [comment] 2019-01-29 10:00
recreated the original project from scratch: it still shows the issue.

the project is attached, renamed from .sb3 to .zip.
[bug-dy.zip](https://github.com/LLK/scratch-gui/files/2807082/bug-dy.zip)

**Comment by towerofnix** [comment] 2019-01-29 17:51
Oh..much investigation later, I have a guess as to what's happening. Perhaps, during the moment after which the sprite has been dropped by the mouse, scripts which are supposed to execute only once per frame (i.e. the loop, since it contains motion blocks) are capable of executing many times? I noticed that if you place a "wait 1 seconds" *before* the repeat-until, it will function as intended. This is certainly a bug.

**Comment by TheLogFather** [comment] 2019-01-29 20:12
I'd point out that the above video shows behaviour while *within the editor*. That means the drop at the end of the drag is being done by Scratch rather than by the user's script. –The behaviour in project page itself is different.

Also, appending the x/y co-ords & value of dy into a list within the "repeat until" loop is quite enlightening...
(Looks to me like it's a case of the Scratch-drag-n-drop in editor overriding the position of the sprite for a short while, which means it isn't able to move, and which then means the loop is allowed to run at 'warp-speed', during which time dy decreases at every pass. By the time the sprite is finally allowed to move, dy has become very negative...)

**Comment by aoloe** [comment] 2019-01-30 07:36
indeed, the bug does not happen in full screen modus and if i put a long enough wait before the loop (in my case 0.1 secs; 0.01 secs is not enough) i don't get the bug either.

sadly, i don't know anything about the scratch internals and can't really help further with the debugging...

**Comment by thisandagain** [comment] 2019-02-04 17:22
@BryceLTaylor Do you mind investigating and creating a repro for this?

**Comment by BryceLTaylor** [comment] 2019-05-22 13:32
I think some of the performance and compatibility work that's happened since this bug was file has fixed this.  The attached .sb3 file works perfectly now when uploaded.  I suspect it's related to some the changes to step threads that went into the vm.  I'm closing this issue.

**Closed by BryceLTaylor** 2019-05-22 13:32 UTC
Labels: bug, compatibility, needs repro, needs-triage, performance

**Comment by aoloe** [comment] 2019-05-22 13:58
Still happens for me in the current online Scratch player.

In the file attached, you have to remove the "wait" block to see the bug.
