### ISSUE TITLE
Invalid costume leads to crash of editor

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#2236] opened 2018-06-04 19:29 UTC
### Expected Behavior

- Editor should not crash when loading projects that may have corrupt or otherwise invalid assets

### Actual Behavior

- Editor crashes with the following in the console:

```
Error: Failed to load project: Error: Document does not appear to be SVG.
    at e.value (lib.min.js:30)
    at g (lib.min.js:230)
    at beginWork (lib.min.js:230)
    at B (lib.min.js:230)
    at o (lib.min.js:230)
    at i (lib.min.js:230)
    at d (lib.min.js:230)
    at Y (lib.min.js:230)
    at C (lib.min.js:230)
    at E (lib.min.js:230)
    at Object.enqueueSetState (lib.min.js:230)
    at e.C.setState (lib.min.js:238)
    at lib.min.js:30
```

### Steps to Reproduce

- Load: https://llk.github.io/scratch-gui/develop/#28272848
- Or: https://llk.github.io/scratch-gui/develop/#24608546

### Operating System and Browser

Mac OS 10.13.4 | Chrome Version 67.0.3396.62 (Official Build) (64-bit)

**Comment by paulkaplan** [comment] 2018-06-28 20:28
The cause of this is exporting from  Illustrator with "Preserve Editing Capabilities" enabled, it pollutes SVGs with a bunch of out-of-spec stuff that cannot be parsed as XML. We'll have to do some special pre-parsing to allow the DOMParser to load those SVGs :(

**Comment by rschamp** [comment] 2018-08-15 15:13
https://llk.github.io/scratch-gui/develop/#28272848 no longer crashes the editor on load, but the errors still appear in the console.

**Comment by paulkaplan** [comment] 2018-12-11 17:17
Going to close this and track it on https://github.com/LLK/scratch-svg-renderer/issues/61, it is the same issue, that one has more examples

**Comment by paulkaplan** [comment] 2019-08-02 14:22
Projects no longer crash

**Closed by paulkaplan** 2019-08-02 14:22 UTC
Labels: bug, compatibility, critical, needs-triage
