### ISSUE TITLE
Auto Save ONLY when project is changed

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#4275] opened 2019-01-07 14:15 UTC
### Expected Behavior

Projects should Autosave only when the project is updated.

### Actual Behavior

Opening a project and seeing inside and then playing the game causes invalidation of the project and autosaves continually during play. I experience this continually on https://scratch.mit.edu/projects/108566337 - Perhaps it's because it's a cloud game? But this really messes up the thumbnail of the game too.

### Steps to Reproduce

Play a game that you have created that updated cloud variables? See that the project changes to 'changed'

### Operating System and Browser

WIndows 10 Chrome

**Comment by griffpatch** [comment] 2019-01-07 18:50
In fact just opening this project or switching sprites from the palette always results in a save being required.

**Comment by paulkaplan** [comment] 2019-01-07 21:00
@griffpatch thanks for reporting this. We just deployed a fix for autosaving that makes the save process much more efficient, and shouldn't pause the editor nearly as much or as badly. This won't fix the problem here, but it should make if _feel_ a lot less bad. Could you try it out on the live site and let me know if you notice a difference?

**Comment by griffpatch** [comment] 2019-01-07 23:12
Yes, it feels a bit more speedy at saving... But the project I'm editing
doesn't have many resources and is fast enough to save... It's just
occuring 'all the time' ;) - It's great to be part of your grand Scratch 3
launch - Congratulations to you all by the way!

**Comment by benjiwheeler** [comment] 2019-01-14 14:41
Thanks, @griffpatch! Your projects have provided lots of inspiration around here!

The auto-save interval was intended to be long enough that it wouldn't tax our systems or bug users, but short enough that users would be able to count on their work being recently saved if they have to close their browser or turn off their computer. But we're open to reconsidering how and when that happens.

Are you still finding it annoying? What in particular is it doing that's feeling distracting or in the way of your work?

**Comment by griffpatch** [comment] 2019-01-14 14:54
The problem is that a project is marked as requiring a save the moment it's opened or running... You don't need to change anything. Is it when a variable is updated? or a sprite costume changed by scripts? This means whenever I open a project it saves a new thumbnail of a project in a strange state... often not what I wanted... in fact I really didn't want it to change. Also, I run the project, click save to get the thumbnail I wanted, then stop the project and click 'see project page' and it saves AGAIN! and again I've lost my intended screenshot.

Auto save is fine, but not when you haven't changed anything, and especially not when playing full screen? :)

Thanks for asking for feedback.

**Comment by BonfireScratch** [comment] 2019-01-21 17:56
@griffpatch I have been suffering from this particular problem too. As a starting point, auto-saving mustn't be done when in full screen or in the project page.

**Comment by ArnoHue** [comment] 2019-01-31 12:40
> @griffpatch I have been suffering from this particular problem too. As a starting point, auto-saving mustn't be done when in full screen or in the project page.

Currently one cannot run his/her own projects on the project page (let alone the editor) without runtime data changes being stored immediately, and getting thumbnail pictures removed. Those runtime data changes might include large lists (e.g. precalculated), which could affect runtime behavior, at a minimum it increases project size and network traffic significantly. I see there is a PR already, the effort to correct this is highly appreciated. Thank you!

As a sidenote, what about an opt-out for autosaving in general? It makes perfect sense per default, but being able to revert to a previous state might be preferrable in certain situations. Esp. as one cannot upload into existing projects right now (if I mess up code, I can only hope to have the previous sprite version exported, and re-import from there). Or am I missing something? Again, thanks a lot!

**Comment by kchadha** [comment] 2019-03-04 15:58
Closing this issue as the issue of running a project triggering an eventual auto save has been resolved and any remaining related issues have been logged in this repository and LLK/scratch-vm with the label 'project saving'.

@ArnoHue you wrote:

> As a sidenote, what about an opt-out for autosaving in general? It makes perfect sense per default, but being able to revert to a previous state might be preferrable in certain situations. Esp. as one cannot upload into existing projects right now (if I mess up code, I can only hope to have the previous sprite version exported, and re-import from there). Or am I missing something? Again, thanks a lot!

The issue you mentioned about not being able to upload a new version of the project from your computer into an existing project is being tracked in #3509. 

As for opting out of autosaving, while I am closing this issue, you should feel free to file that as a feature request in a separate issue.

**Closed by kchadha** 2019-03-04 15:58 UTC
Labels: bug, critical, has patch
