### ISSUE TITLE
Can't scroll down in block workspace, it scrolls me up quickly instead

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2220] opened 2018-06-01 20:35 UTC
### Expected Behavior

Scroll works the same across browsers

### Actual Behavior

On https://llk.github.io/scratch-gui/develop/#226951058 when I try to mouse scroll down over the blocks workspace I scroll up twice as fast instead. Scrolling up is very slow.

### Steps to Reproduce
I haven't been able to reproduce. Scrolling is very slow in firefox both up and down now.

### Operating System and Browser
Windows Firefox

**Comment by sjhuang26** [comment] 2018-06-03 01:01
I tried to repro this. It works fine on Chrome, but on Firefox, the scrolling is in the correct direction but is very slow. However, I did not see the behavior where "when I try to mouse scroll down over the blocks workspace I scroll up twice as fast instead."

**Comment by towerofnix** [comment] 2018-06-03 12:27
Potentially related to LLK/scratch-blocks#1190 (which has a pending PR LLK/scratch-blocks#1427 fixing it).

**Comment by BryceLTaylor** [comment] 2018-06-04 21:16
I'm unable to reproduce the original issue where you scroll backwards.  I am however seeing the issue where scrolling is incredibly slow on Firefox.  I'm seeing it on both Windows and Mac.  I'm seeing slow scrolling with both the mouse wheel and two finger scrolling on the workspace.  I also found this issue related to scrolling: https://github.com/LLK/scratch-gui/issues/2240

I'm also seeing slow scrolling on the blocks palette in Firefox with the mouse wheel, but not with two finger scrolling.

**Comment by BryceLTaylor** [comment] 2018-06-04 21:18
We may want to update the name of this issue, or move the slow scrolling into a new issue and close this one.

**Comment by towerofnix** [comment] 2018-06-05 00:37
>or move the slow scrolling into a new issue and close this one.

@BryceLTaylor There already is an issue for that - LLK/scratch-blocks#1190 - and a PR fixing it - LLK/scratch-blocks#1427.

**Closed** 2018-07-09 15:29 UTC
Labels: bug
