### ISSUE TITLE
Negative numbers in some *BLOCKS* display incorrectly for RTL languages

### ISSUE THREAD

**Issue by Farshidmi** [LLK/scratch-gui#7016] opened 2021-04-06 12:59 UTC
Hi
In these blocks we have this problem, so kids couldn't find bug and It confuses them. (maybe this is the most important **bug** in RTL languages.)
Kindly fix these blocks at first :

![image](https://user-images.githubusercontent.com/45791173/113714157-590f4f80-96fd-11eb-810c-9db753985651.png)

I checked the other blocks and they are OK.
Other issue about negative numbers in other places describe [here](https://github.com/LLK/scratch-gui/issues/5483). 
Regards

_Originally posted by @Farshidmi in https://github.com/LLK/scratch-gui/issues/5483#issuecomment-814055498_

**Comment by apple502j** [comment] 2021-04-06 19:25
Duplicate of LLK/scratch-blocks#2043

Note that "set variable" block is probably intentional, as that block can be used for both LTR numbers and RTL text, and fixing it for one means breaking it for the other.

**Comment by Farshidmi** [comment] 2021-04-07 09:36
> Duplicate of [LLK/scratch-blocks#2043](https://github.com/LLK/scratch-blocks/issues/2043)
> 
> Note that "set variable" block is probably intentional, as that block can be used for both LTR numbers and RTL text, and fixing it for one means breaking it for the other.

Hi, 
Text is not very important and the **number** is most common issue in this block (set variable).
If all characters in this block are Persian or other rtl language characters , it displayed correctly (and no matter this block is RTL or LTR): 

![image](https://user-images.githubusercontent.com/45791173/113845298-9b429a80-97aa-11eb-800b-e428ae91bb07.png)

I know in some cases that we use both LTR and RTL characters , Text displayed incorrectly but for kids, I suggest it is better this block show numbers correctly. 

Regards

**Comment by chrisgarrity** [comment] 2021-04-13 17:03
These should all be documented as [bugs in the scratch-blocks](https://github.com/LLK/scratch-blocks/issues?q=is%3Aissue+is%3Aopen+rtl+number) repo now. There are bugs on gui for monitors (#5483) and sprite info (#7037)

**Closed as completed by chrisgarrity** 2021-04-13 17:03 UTC
Labels: localization
