### ISSUE TITLE
>,<,=,+,-,*,/ operator blocks do not have the option change their signs

### ISSUE THREAD

**Issue by SAODTHEKING** [LLK/scratch-gui#2989] opened 2018-08-25 17:37 UTC
### Expected Behavior

like 2.0, when i right click on the operator block ([...]<[...]), it gives me options to change it to >/=. 
![image](https://user-images.githubusercontent.com/22136356/44621044-0106e000-a8a8-11e8-8289-c619c4b42d55.png)

Same goes for 
+,-,*,/W
### Actual Behavior

In 3.0, when i right click on it, i dont get the option to change, and i need to remove it and get a new operator block with the desired </>/=
![image](https://user-images.githubusercontent.com/22136356/44621055-36abc900-a8a8-11e8-99a2-2140a94d257a.png)

Same goes for 
+,-,*,/
### Steps to Reproduce

Right click on the operator block on 3.0

### Operating System and Browser

Win10/Chrome

This is more of a convenience issue but, it is really annoying and time wasting to have to remove whole sections of scripts just to change the signs of the operator blocks.

**Comment by Kenny2github** [comment] 2018-08-26 05:29
Duplicate of LLK/scratch-blocks#1383

**Comment by SAODTHEKING** [comment] 2018-08-26 13:09
@kenny2github its been 6 months from that post and no one fixed the issue! dont u think it needs a reminder?

**Comment by Kenny2github** [comment] 2018-08-27 02:26
That issue is in the "Backlog" milestone, which means it will only be looked at after release. Have patience - all Backlog issues will be handled once 3.0 has been released.

**Closed** 2018-08-27 04:02 UTC

**Comment by traincrisis** [comment] 2022-05-30 08:31
You can use Scratch Add-ons browser extension to add switching.
![Screenshot 2022-05-30 at 11-31-05 Scratch - Scratch Blocks In Vector ALL](https://user-images.githubusercontent.com/97363059/170951630-a3912f8c-2b87-4aae-9753-1de192e8accf.png)
