### ISSUE TITLE
Warning user before deleting sprite

### ISSUE THREAD

**Issue by NilsTheBest** [LLK/scratch-gui#4702] opened 2019-03-31 12:42 UTC
### Expected Behavior

When you delete a sprite, a warning pops up and says something on the lines of "Are you sure you want to delete the sprite "x"? This action is irreversible."
This could also potentially lower the amount of accidental sprite deletions.

### Actual Behavior

When you delete a sprite, the sprite is just deleted.

### Steps to Reproduce

* Create a sprite
* Delete a sprite

### Operating System and Browser

N/A

**Comment by paulkaplan** [comment] 2019-08-02 14:58
Closing as a duplicate of https://github.com/LLK/scratch-gui/issues/4311

**Closed by paulkaplan** 2019-08-02 14:58 UTC
