### ISSUE TITLE
Right click makes page scroll

### ISSUE THREAD

**Issue by csf30816** [LLK/scratch-gui#714] opened 2017-09-28 00:41 UTC
### Expected Behavior

_Please describe what should happen_
When right clicking a dialog should popup and page width/height should remain the same

### Actual Behavior

_Describe what actually happens_
When right clicking a dialog pops up that changes the page's width/height by it's width

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Go to https://llk.github.io/scratch-gui/ and right click.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

Note: this can be fixed in CSS by adjusting the dialogs position from `absolute` to `fixed`

**Comment by Kenny2github** [comment] 2017-09-28 02:33
Duplicate of #548 (also closed and moved to LLK/scratch-blocks#1023)

**Comment by rschamp** [comment] 2017-10-02 14:36
Thanks for the report @csf30816 and to @Kenny2github for finding the dupe.

**Closed by rschamp** 2017-10-02 14:36 UTC
