### ISSUE TITLE
Sprite icon gets smaller when working in the paint editor

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1471] opened 2018-02-21 16:45 UTC
### Expected Behavior
When you edit a sprite in the costumes tab (more specifically the paint editor), the sprite icon should NOT get change or get smaller

### Actual Behavior
When you edit a sprite in the costumes tab (more specifically the paint editor), then the sprite icon gets smaller
<img width="1652" alt="scratch_3_0_gui" src="https://user-images.githubusercontent.com/3812168/36490414-2fef995a-16f6-11e8-8bd7-c3f9273c67d0.png">

### Steps to Reproduce
1. Open a project in 3.0
2. Click on a sprite 
3. Click on the Costumes tab to visit the Paint Editor
4. Click on any button in the Paint Editor or make an edit to the sprite
5. Watch for the sprite icon on the stage and in the costumes list get smaller

### Operating System and Browser
Chrome 64

**Comment by mrjacobbloom** [comment] 2018-02-21 17:17
Duplicate of #762 and #1431

**Comment by thisandagain** [comment] 2018-02-26 19:30
Leaving this open as a tracking issue. Marking as critical and assigning to @rschamp for follow-up / resolution in March.

**Closed** 2018-02-27 16:09 UTC
Labels: bug, critical, has-patch
