### ISSUE TITLE
Language reporter in language extension does not get initialized in player-only mode

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4451] opened 2019-01-29 14:06 UTC
### Expected Behavior

_Please describe what should happen_
If your language is set to something other than English*, the language reporter should default to the users locale. 

* If it's not in the set of languages supported by the translate extension, it should still default to English.

### Actual Behavior

_Describe what actually happens_

The language is always English when viewing the project on the project page. When you 'see inside', the language gets set to the current language.

### Steps to Reproduce

- Set your language to a supported translate extension language (e.g., French, Spanish, German, etc)
- View a project (project page view) that loads the translate extension, and that has the language monitor checked.
- Click green flag to see the monitor (it's English)
- Click 'see inside', the stage re-renders and the monitor is the language chosen in the first step.

### Operating System and Browser

Mac OSX, Chrome (but probably all)

**Comment by apple502j** [comment] 2019-01-30 10:50
Duplicate of #4253

**Closed** 2019-01-30 13:39 UTC
