### ISSUE TITLE
Extensions Stick Around

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#6196] opened 2020-09-19 00:09 UTC
### Expected Behavior

If you click File > New on a project with extensions, the extensions should be cleared (before reload) on the new project.
### Actual Behavior

They stick around until reload
### Steps to Reproduce

Create a new project
Add an extension (Or extensions)
Click File > New
See Extensions
### Operating System and Browser

ChromeOS

**Comment by apple502j** [comment] 2020-09-19 07:31
Duplicate of LLK/scratch-vm#1731

**Comment by BryceLTaylor** [comment] 2020-09-22 15:27
Closing as duplicate

**Closed as completed by BryceLTaylor** 2020-09-22 15:27 UTC
