### ISSUE TITLE
Text Overflows Container for the "Extensions", "Add Sprite", and "Add backdrop" Items in Safari

### ISSUE THREAD

**Issue by dalearn** [LLK/scratch-gui#955] opened 2017-11-28 01:22 UTC
The label text on The "Extensions", "Add Sprite", and "Add Backdrop" buttons overflows the surrounding box in Safari.

Chrome (The Expected Behavior)
![untitled](https://user-images.githubusercontent.com/16820599/33297687-63d8ad26-d3b0-11e7-86c4-ce555c2301ba.png)

Safari 11.0.1 
![untitled1](https://user-images.githubusercontent.com/16820599/33297721-9abe4c10-d3b0-11e7-9784-7df93c022d86.png)

Edit:
I had my max text size set to 12 instead of the default 9 after setting it back to 9 it looks just fine.  Should we Leave it as it is and hope that people don't have that setting modified in any way or should we try to find a workaround?

**Comment by VutonDesign** [comment] 2017-11-28 08:12
Seems to be a duplicate of #864

**Comment by thisandagain** [comment] 2017-11-28 13:26
Tracking in https://github.com/LLK/scratch-gui/issues/864

**Closed by thisandagain** 2017-11-28 13:26 UTC
