### ISSUE TITLE
File>Upload from your computer gives the wrong name to both projects

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4123] opened 2018-12-18 15:09 UTC
### Expected Behavior

If you have a project open and you choose File>Upload it should result in the old project having the old project name and the new, uploaded project having the name of the uploaded project.

### Actual Behavior

The old project gets the name of the uploaded project and the uploaded project gets the name "Untitled - ##"

### Steps to Reproduce

(you may need to make and download a scratch project)
Create a new project
Add a backdrop and a sprite to the project
Save the project
Give the project a title
Choose File>Load from your computer
Choose a scratch project from your computer
Note: your project has the title Untitled - ## and the contents of the uploaded project
Navigate to My Stuff
Note: there is a project called Untitled - ## that has a thumbnail for the uploaded project and a second project (older) that has a thumbnail that matches the project made in the steps above but the title of the uploaded project.
Open the project made in the steps above that now has the wrong name
Note: it has the correct contents.

### Operating System and Browser

Mac Chrome

**Comment by paulkaplan** [comment] 2018-12-18 21:32
@BryceLTaylor fix for this was just merged into develop, should be good to test on staging soon.

**Comment by benjiwheeler** [comment] 2018-12-19 02:42
Reopening this because #4120 solved only half of the problem:
* the existing/previous project is no longer renamed (most important part! yay!)
* the newly uploaded project is still given a generic name ("Untitled-6")

The core issue is a bit tricky... 

Basically the `project-state` goes through the states:
1. loading upload ->
2. showing without id ->
3. creating new

It's at that creating new step that we want to set the new title. The problem is that from that point, you can look back one state (using prevprops) easily, but there’s no immediately obvious way in `project-saver-hoc` to say “oh, we’re creating a new project because of an upload, it’s not a new default project”
but at least the old project isn’t being renamed!

**Comment by benjiwheeler** [comment] 2018-12-19 14:10
Tracking remaining part of issue in https://github.com/LLK/scratch-gui/issues/4145

**Closed by benjiwheeler** 2018-12-19 14:10 UTC
Labels: bug, critical
