### ISSUE TITLE
Many blocks untranslated when loaded in another language

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-gui#4476] opened 2019-02-04 09:53 UTC
### Expected Behavior

_Please describe what should happen_
When the editor is loaded with a language other than English, the blocks should be translated.

### Actual Behavior

_Describe what actually happens_
If you have your language set to something other than english about 30% of the blocks still show up in the toolbox in English. When you drag them to the workspace they appear translated.

![untranslated-onload](https://user-images.githubusercontent.com/399209/52200977-681ebc80-286a-11e9-9390-dfe36817411d.gif)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Set your language to something other than English for loading the editor. I.e. change your language on the website before opening the editor, or load the editor with a locale: https://llk.github.io/scratch-gui/develop/?locale=es

All of the basic blocks should be translated, but many will come up in English. Switch to another language, then back to the original, and the blocks will be translated.

I think this regression may be due to the perf changes. /cc @paulkaplan @picklesrus

**Comment by paulkaplan** [comment] 2019-02-04 13:41
Oh no! That definitely looks like a regression. I'll look into this right away.

**Comment by thisandagain** [comment] 2019-02-04 17:41
Resolved in #4478

**Closed** 2019-02-04 17:41 UTC
Labels: bug, critical, has patch, localization
