### ISSUE TITLE
Naming a custom block "%s" triggers an error 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1348] opened 2018-01-26 18:30 UTC
### Expected Behavior

It should be possible to safely name a custom block with any string.

### Actual Behavior

Naming a custom block "%s" triggers an error: 

`Uncaught Value inputs and statement inputs must have non-empty name.`

Thanks to a Scratch forum user for catching this one!

**Comment by thisandagain** [comment] 2018-01-26 18:31
Duplicate of #1347

**Closed by thisandagain** 2018-01-26 18:31 UTC
Labels: bug
