### ISSUE TITLE
Language menu renders differently in Firefox

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#1308] opened 2018-01-18 22:08 UTC
![image](https://user-images.githubusercontent.com/1786240/35123892-11b78180-fc72-11e7-9931-3f70ddef944a.png)

### Operating System and Browser

Mac OS 10.12.6, Firefox 57.0.2 (64-bit)

**Comment by dgnball** [comment] 2018-01-19 21:46
Is this a duplicate of #816 ?

**Comment by thisandagain** [comment] 2018-02-01 23:12
Tracking in https://github.com/LLK/scratch-gui/issues/816

**Closed by thisandagain** 2018-02-01 23:12 UTC
Labels: bug, feedback form, help wanted
