### ISSUE TITLE
Clicking on a variable block doesn't show a callout with its value

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#519] opened 2017-07-07 15:20 UTC
### Expected Behavior

Clicking a variable block should show a say bubble with its value, the way x position does for example

### Actual Behavior

Nothing happens when clicking the variable block

### Steps to Reproduce

1. Create a new variable
2. Click on the block in the flyout
3. Drag the block to the scripts workspace
4. Click on the block in the workspace

**Comment by paulkaplan** [comment] 2017-10-20 18:28
So finally figure out the cause of this, and it isn't related to the recent stuff that broke with the toolbox. I'm going to close it here because I'm tracking it (with the cause) here: https://github.com/LLK/scratch-blocks/issues/1160

**Closed by paulkaplan** 2017-10-20 18:28 UTC
Labels: bug
