### ISSUE TITLE
Can't save project if any block contains a "\b" message

### ISSUE THREAD

**Issue by JinXJinX** [LLK/scratch-gui#5379] opened 2020-01-11 00:00 UTC
### Expected Behavior

project can be saved at anytime

### Actual Behavior

![image](https://user-images.githubusercontent.com/12160296/72194134-78281000-33da-11ea-9167-868b24cab0c2.png)

### Steps to Reproduce

1. open scratch
2. add a "ask __ and wait" block
3. input "\b"
4. save project
5. you will see this message "Project could not save"

### Operating System and Browser

Mac OS 10.15.2
Chrome 79

**Comment by apple502j** [comment] 2020-01-11 00:11
Duplicate of  LLK/scratch-parser#56

**Comment by benjiwheeler** [comment] 2020-01-11 03:56
Thanks, @JinxJinx and @apple502j . Looks like this is a version of a bug we've partially fixed before, for other control characters. We should take a look at widening the list of characters we exclude.

See https://github.com/LLK/scratch-gui/issues/4767#issuecomment-487672327

**Closed** 2020-01-11 19:44 UTC

**Comment by picklesrus** [comment] 2020-01-13 13:56
@JinXJinX how did you input the \b character? When we were working on this problem before, it was difficult understand the impact because we couldn't figure out how to type one using a US keyboard. I tried a Japanese IME but didn't figure out how to type it using that either.  Thanks!

**Comment by apple502j** [comment] 2020-01-13 15:20
@picklesrus Not backspace, but the string "\b" - or, `\\b` when encoded.
![image](https://user-images.githubusercontent.com/33279053/72267575-a409f680-3663-11ea-9de8-fa9ecc9886d0.png)

**Comment by picklesrus** [comment] 2020-01-13 15:23
oh! Yeah, that was an unfortunate side effect of what we did to avoid the backspace causing problems :-/

**Comment by SamuelMcGowan** [comment] 2021-02-05 21:43
If someone uploaded "\b" to a cloud variable and the owner's project fetched and decoded the cloud variable it would make the project unsaveable.
