### ISSUE TITLE
Inconsistant naming of example sprites

### ISSUE THREAD

**Issue by 2br-2b** [LLK/scratch-gui#5843] opened 2020-06-02 19:24 UTC
### Expected Behavior

All of the example sprites would have the same naming conventions: for example, sprites without duplicates would just have their names with no numbers after them, while ones with duplicates would follow the same conventions

### Actual Behavior

The sprite names are inconsistent.
 - There are the sprites `Arrow1` and `Balloon1`, but no `Arrow2` or `Balloon2`.
 - Sometimes, the sprites have spaces between the word and the number (`Characters 1` and `Characters 2`) and sometimes they don't (`Button1` through `Button5`).
 - Sometimes the first sprites don't even have a number after their name (`Convertible` and `Convertible 2`).
 - Sometimes, the names are confusingly similar (`Cloud` and `Clouds`), but that's probably a different issue.

### Steps to Reproduce

Open Scratch, say choose a new sprite, and comb through the names of the sprites closely.

### Operating System and Browser

Any

--------------
To fix, one naming convention needs to be determined for all of the default sprites.

**Comment by Explosion-Scratch** [comment] 2020-06-02 23:37
Yes, this would be an easy fix, should be fixed.

**Comment by 2br-2b** [comment] 2020-06-03 00:39
What naming convention should be used? I’m thinking we use ‘Characters 1’, ‘Characters 2’, etc.

I’ll open a different issue for ‘Cloud’ vs ‘Clouds’

**Comment by apple502j** [comment] 2020-06-03 02:39
Duplicate of #4218

**Comment by BryceLTaylor** [comment] 2020-06-03 15:59
I'm closing as a duplicate of #4218

**Closed by BryceLTaylor** 2020-06-03 15:59 UTC
Labels: Low Severity, Medium Impact, priority 4
