### ISSUE TITLE
Cannot delete lists by right-clicking in toolbox like you can with variables

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2528] opened 2018-06-29 20:54 UTC
### Expected Behavior

Right clicking on a list in the toolbox should have a delete option.

### Actual Behavior

There is no context menu.

### Steps to Reproduce

Right click on a list in the toolbox.

### Operating System and Browser

Windows 10 Chrome 67

**Comment by apple502j** [comment] 2018-06-30 05:46
Duplicate of #1968

**Comment by thisandagain** [comment] 2018-07-09 13:12
Tracking in https://github.com/LLK/scratch-gui/issues/1968

**Closed by thisandagain** 2018-07-09 13:12 UTC
