### ISSUE TITLE
() of () reporter doesn't work on sprite if it's named Stage

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#1210] opened 2018-01-09 01:17 UTC
### Steps to Reproduce
Actual stage. The name shows up as \_stage\_
<img width="242" alt="screen shot 2018-01-08 at 20 19 29" src="https://user-images.githubusercontent.com/2855464/34700453-3d4b4200-f4b1-11e7-9d4b-848f5387b268.png">
The sprite named Stage. Its direction should be 90
<img width="228" alt="screen shot 2018-01-08 at 20 19 21" src="https://user-images.githubusercontent.com/2855464/34700448-39690582-f4b1-11e7-84e0-8943bd5a1bae.png">

1. Name a sprite Stage
2. Now you have to add any other sprite because of bug https://github.com/LLK/scratch-gui/issues/1207
3. Go to () of () block in sensing. There's 2 "Stage"s in the 2nd dropdown.

### Actual Behavior
Both of them report values for the stage, and neither of them report values for the sprite named Stage.

### Expected Behavior

Maybe you shouldn't be allowed to name a sprite Stage? When you try to name a sprite \_stage\_ it doesn't work

### Operating System and Browser
Mac OSX Chrome

**Comment by amazinigmech2418** [comment] 2018-01-10 03:09
The sprite named stage shouldn't be allowed. Maybe add code like this to filter the code:
`
function filter(name) {
var toFilter =["Stage","_stage_"];
if (toFilter.indexOf(name)===-1) {
// code to add block
} else {
// error pop-up code
}
}
` Sorry if the enters don't show.

**Comment by thisandagain** [comment] 2018-01-12 15:29
We have removed support for reporters for this block (as per Scratch 2.0).

**Comment by thisandagain** [comment] 2018-01-12 15:37
Assigning to @ericrosenbaum to clarify what the issue is.

**Comment by ericrosenbaum** [comment] 2018-01-12 15:41
Clarification: this bug is not related to monitors. The bug is caused by naming a sprite "Stage." If you have a sprite named "Stage", this block will have a menu that contains two identical entries ("Stage" and "Stage") and both will report the value of the selected property for the actual Stage, and not the sprite.

**Comment by fsih** [comment] 2018-01-12 18:39
@paulkaplan notes that not allowing Sprites to be named Stage might not work, since there are 2.0 projects with sprites named Stage

**Comment by hedgehog125** [comment] 2018-01-12 19:19
It might also make sense if  it's styled differently to sprites in the pulldown to reduce confusion.

**Comment by amazinigmech2418** [comment] 2018-01-12 21:07
Naming a sprite Stage shouldn't be allowed, so maybe a filter should be added.

**Comment by amazinigmech2418** [comment] 2018-01-12 21:08
@fsih Maybe, it could rename the sprite to Stage1 instead.

**Comment by ericrosenbaum** [comment] 2018-02-12 15:10
Investigating this again: generally, creating a sprite called "Stage" causes trouble in any block with a dynamic menu of sprites (go to, glide to, point towards, create clone of, direction to, and the "of" block). In cases where the coordinates are retrieved, it uses (0, 0) (i.e. the internal coordinates of the actual stage?), instead of the coordinates of the sprite called Stage. 

We look up sprites by name for these purposes (in the runtime, getSpriteTargetByName). So we generally need to prevent duplicate names. 

Looks like we just need to add logic to the code that appends numbers to new names to prevent duplicates, to catch the name "Stage" (as @amazinigmech2418 pointed out).

**Comment by fsih** [comment] 2018-02-12 15:18
@paulkaplan mentioned to me that sprites named Stage are pretty common in existing projects

**Comment by ericrosenbaum** [comment] 2018-02-12 15:42
Hm... so at best changing the renaming behavior will prevent this problem in the future. I'm trying to figure out how we should deal with the existing projects.

I guess there are actually two problems:

A) If there's a sprite named "Stage", selecting it in the menu instead selects the actual stage, with incorrect results (the "go to" block with "Stage" selected for example will go to 0, 0 instead of the Stage sprite)
B) In the "of" block (but not the others, which do not list the actual stage), there will be two identical entries in the menu for "Stage". 

Ideas:

-  Always look up sprites by ID, which would create the right behavior, even for the menu containing two identical names. This seems like a big change.
- Fix the blocks that use a sprite menu by preventing the lookup from returning the actual stage. This would work for everything but the "of" block, which needs to be able to return the stage. We could fix the "of" block separately by always using IDs for the lookup there. Note that there is another bug with the "of" block related to the stage [here](https://github.com/LLK/scratch-gui/issues/1224). 
 
Any thoughts on this @paulkaplan @rschamp @cwillisf ?

**Comment by fsih** [comment] 2018-02-12 16:00
The 2nd solution seems pretty good, given that the "of" block will need special treatment for the stage anyway (https://github.com/LLK/scratch-gui/issues/1224)

Sprite menu explicitly filters out stage:
https://github.com/LLK/scratch-gui/blob/6526445fb7ae4f763d8521a3c6352ba78491fb1d/src/lib/blocks.js#L53

So anywhere it gets added is a special case:
https://github.com/LLK/scratch-gui/blob/6526445fb7ae4f763d8521a3c6352ba78491fb1d/src/lib/blocks.js#L128

**Comment by ericrosenbaum** [comment] 2018-02-12 20:46
After some experiments, it appears that simply changing the runtime's getSpriteTargetByName function so that it skips the stage fixes the original problem. Now you can use the "go to" block to go to a sprite called "Stage," and use other blocks as with the dynamic sprite menu as expected. PR on its way.

It seems better to leave out the change to renaming, so that you can still create a sprite called "Stage" if you want to.

It turns out the import behavior for SB2s with a sprite called "Stage" is incorrect, so I'll file another issue for that.

**Closed** 2018-02-14 00:44 UTC
Labels: bug, needs-discussion
