### ISSUE TITLE
blocks comment bug: when writing comments in Chinese and more 12 characters

### ISSUE THREAD

**Issue by houcy** [LLK/scratch-gui#5667] opened 2020-04-22 01:46 UTC
### Expected Behavior

When using Chinese to write blocks comments and collapse the comment, it should be unfolded successfully.

### Actual Behavior

When writing blocks comments in Chinese, and the length of Chinese characters exceed 12, if collpase the comment, it will never be unfolded.

### Steps to Reproduce
1. Create a simple program, then add block comment.
2. Write comment in Chinese and more than 12 characters.
3. Collpase the comment.
4. Try to unfold the comment by clicking the left side triangle icon in comment.

### Operating System and Browser
Windows 10, Scratch Desktop and www version

**Comment by apple502j** [comment] 2020-04-22 01:59
Duplicate of LLK/scratch-blocks#1680

**Comment by houcy** [comment] 2020-04-22 03:27
Thanks for reply.
For Chinese comment, set the max label length to 8, it's verified fine.
Blockly.ScratchBlockComment.MAX_LABEL_LENGTH = 8;

**Comment by BryceLTaylor** [comment] 2020-04-22 15:44
Closing because it's a Duplicate of https://github.com/LLK/scratch-blocks/issues/1680

**Closed by BryceLTaylor** 2020-04-22 15:44 UTC
