### ISSUE TITLE
Deleting custom block definition doesn't delete from toolbox

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#1128] opened 2017-12-26 13:08 UTC
### Expected Behavior

When you delete a block definition, if all uses of the block are removed the definition AND it's instance in the toolbox will disappear

### Actual Behavior

The definition disappears, but not the block

### Steps to Reproduce

1. Create a custom block
2. Delete definition
3. Look in toolbox

### Operating System and Browser

Windows 10 Chrome 63

**Comment by paulkaplan** [comment] 2017-12-27 16:25
Thanks for reporting this. It has already been logged where it will be fixed, on the scratch-blocks repo, so I'm going to close this as a duplicate of https://github.com/LLK/scratch-blocks/issues/1295

**Closed by paulkaplan** 2017-12-27 16:25 UTC
