### ISSUE TITLE
sb-file-uploader.jsx throw TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by qm88888888** [LLK/scratch-gui#4884] opened 2019-05-31 02:55 UTC
When you upload sb file, if you multiple clicks sb3 file,  the web may proceed with error。
![image](https://user-images.githubusercontent.com/18499175/58678341-f37c0a80-8391-11e9-8848-c99d8e58dbd4.png)
Reason： The program execute componentWillUnmount Function, but onload need reader object. It may not be the reason. Please try to reproduce this bug. Thanks.

**Comment by benjiwheeler** [comment] 2019-06-03 15:27
Could you provide the sb file you uploaded, or the url of the project on the site?

**Comment by qm88888888** [comment] 2019-06-04 03:03
I used github develop branch, Any sb3 file  can be reproduced。
![image](https://user-images.githubusercontent.com/18499175/58848196-428aae00-86b8-11e9-870e-57499ad7e6cb.png)
Please multiple clicks. not double click, please unlimited click.

**Comment by huaerzx** [comment] 2019-11-06 05:36
@benjiwheeler 
I have the same problem with scratch desktop, and  its not happened in the chrome
[Desktop.zip](https://github.com/LLK/scratch-gui/files/3812667/Desktop.zip)

**Comment by apple502j** [comment] 2019-11-25 05:14
Duplicate of #4332

**Comment by benjiwheeler** [comment] 2019-12-11 14:58
Thanks for noting the duplicate, and linking the PR, @apple502j

**Closed by benjiwheeler** 2019-12-11 14:58 UTC
