### ISSUE TITLE
Adding the stop all block to a "waiting until" stack didn't stop all

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-gui#415] opened 2017-06-05 19:44 UTC
### Expected Behavior

A lot of times, when you add a block to an active stack of blocks, the change immediately takes effect. In this case, that didn't seem to happen here, when Jie showed it to me. The block also didn't have the active yellow highlight, but it was still "active" kind of - the "wait until" block makes it a little confusing whether the stack is active while it's waiting until, or only when what it's waiting until happens...?

### Actual Behavior

Jie reported during the Catch Game internal playtest (6/2/17):
> If I don't have a Stop All block and run the script, and then add the Stop All while the script is running, code will not stop even after you reach greater than the win score.  May have something to do with not resetting properly (since I noticed the "win" sprite is visible even before actually winning)

> Script running without stop block
<img width="566" alt="screen shot 2017-06-05 at 10 47 40 am" src="https://cloud.githubusercontent.com/assets/1320456/26788826/7295f3ae-49dc-11e7-85e9-cd67c181e99f.png">

> Script still running after Stop All block added and winning score reached
<img width="443" alt="screen shot 2017-06-05 at 10 48 34 am" src="https://cloud.githubusercontent.com/assets/1320456/26788870/9832ada0-49dc-11e7-8325-e8548467e5b4.png">

### Operating System and Browser

_Mac OS, Chrome_

**Comment by paulkaplan** [comment] 2017-06-06 18:48
I'm wondering if this may have had to do with some of the other problems that were occurring at the same time. I wasn't able to reproduce. I tried two different projects:

![stop-all-seems-to-work](https://user-images.githubusercontent.com/654102/26846215-fc196ca6-4ac6-11e7-8c36-1349c4072897.gif)

![stop-all-seems-to-work-2](https://user-images.githubusercontent.com/654102/26846223-04867e92-4ac7-11e7-824b-9e8ee3ebbf74.gif)

**Comment by paulkaplan** [comment] 2017-06-07 13:09
@jwzimmer do you think you could try to find a way to reproduce the original error?

**Comment by jwzimmer** [comment] 2017-06-07 14:52
### Repro
I repro'd this by following the steps in the Catch Game card (since I figured that was how Jie encountered this during the playtest).

**I see two issues while using the stack in the "You Win!" card (there are errors in the console as well):**
- The green flag sprite I am showing/ hiding when the player wins does not get re-hidden on green flag until the 2nd time you have clicked green flag after triggering the "show" of the green flag sprite initially
  - This happens whether or not the "stop all" block is part of the stack
- If the stop all block is present, the project will not restart on green flag after it is triggered; you have to click one of the stacks in the project in order to restore being able to use green flag to start the project

**More detailed description***
- One of the cards/ steps near the end, "You Win!" has the stack that seems to break
- The first time playing the project with that stack, the green flag sprite hid when the score became greater than 10, and the rest of the project stopped, as expected
- **The green flag sprite disappears on green flag only the 2nd time you click green flag after a play session in which the green flag sprite was shown**
- The score variable does reset consistently on green flag, in contrast to the show/ hide state of the green flag sprite
- If the stack is playing, and the score has not triggered the wait until condition, and you add the stop all block, when you do trigger the condition, the stop all block does work (stops the project)
- If the stack has the stop all block when you start playing it, then it does trigger the stop all block appropriately, but subsequently, green flag will not re-start the project (doesn't start playing, does not reset score to 0) no matter how many times you click it.
- You have to click any stack in the project to get out of this state; when you click the stack, that stack will start, then when you click green flag, the project will play as usual (clicking on the stack seems to "fix" being able to start the project with green flag)
- If I remove the "stop all" block at the end of the stack, the project can be re-started with the green flag after being stopped with red stop sign; the stop all block seems to be causing the issue where the project won't re-start on green flag

**Errors in the console**
<img width="1280" alt="screen shot 2017-06-07 at 10 38 43 am" src="https://user-images.githubusercontent.com/1320456/26884325-83c8d2bc-4b6d-11e7-873f-1f47c44e1450.png">

**All the contents of my project**
<img width="1280" alt="screen shot 2017-06-07 at 10 51 32 am" src="https://user-images.githubusercontent.com/1320456/26885011-51f44aa8-4b6f-11e7-9ef4-8d08b19caaec.png">
<img width="1279" alt="screen shot 2017-06-07 at 10 51 25 am" src="https://user-images.githubusercontent.com/1320456/26885010-51f3f256-4b6f-11e7-9594-261c4dd8f2f3.png">
<img width="1280" alt="screen shot 2017-06-07 at 10 51 15 am" src="https://user-images.githubusercontent.com/1320456/26885012-51fe12b8-4b6f-11e7-9c7e-9aa2377d9c15.png">

**Comment by paulkaplan** [comment] 2017-06-07 15:23
Alright so the part of the issue having to do with clicking the green flag again and it not working, here is what is going on: 

It seems like a "race condition" of sorts in the way the catch game code was designed. The stack that waits for the variable to be > 10 does not initialize the variable to zero, another stack does that. This means, depending on the execution order, the "you win" stack can fall through directly to stop-all. 

In scratch 2 there is an issue with the catch game code also, requiring you to click the green flag twice to get it to run again. 

Since we make no guarantees about execution order, the "you win" stack in the catch game cards should look like the right instead of the left:

![image](https://user-images.githubusercontent.com/654102/26886508-9202c8f0-4b73-11e7-9cbf-3965b33f3e0a.png)
 
cc @cwillisf about execution order and @thisandagain about the cards being wrong!

**Comment by thisandagain** [comment] 2017-06-07 15:36
O_O Good catch. @carljbowman can you make this change in the cards?

**Comment by ericrosenbaum** [comment] 2017-06-07 15:37
I SEE WHAT YOU DID THERE

**Comment by carljbowman** [comment] 2017-06-07 15:54
We are removing this card from the set for the playtest as it requires the Paint Editor.

While it's not ideal, double clicking the Green Flag does cause a reset in 2.0, which highlights a difference in order of execution between 2.0 and 3.0. Do we have a sense as to why this might be the case?

**Comment by paulkaplan** [comment] 2017-06-08 14:40
I'm going to close this now that @jwzimmer has separated the other part of the issue and we this issue cannot be closed by any code changes in GUI.

**Closed by paulkaplan** 2017-06-08 14:40 UTC
Labels: needs repro
