### ISSUE TITLE
Issues found in bughunt and exquisite playtest on 11/9/18

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3732] opened 2018-11-13 16:25 UTC
* [x] On Android Tablet Chrome: Piano notepicker appeared fine at first, but then later it appeared at half width @benjiwheeler 
![image14](https://user-images.githubusercontent.com/1088291/48427209-4368ec00-e736-11e8-9894-dcd316c7ff32.png)
![image15](https://user-images.githubusercontent.com/1088291/48427269-63001480-e736-11e8-81ee-979976db69de.png)
![image16](https://user-images.githubusercontent.com/1088291/48427278-672c3200-e736-11e8-82bd-0d3053d7492e.png)
To replicate:
Use Android Tablet Chrome
Start with new default project
add music extension
drag out play note block
tap on “60” (note field) -- width of picker is good!
tap on “0.25” (beats field) and bring up number picker
tap away from the number picker to dismiss
tap on “60” (note field) -- width of picker is too narrow! 
* [x] Notepicker.
Click and drag to play different notes. When you drag outside the notepicker (left or right), the sprite info area and stage header also get highlighted. @chrisgarrity 
* [x] Connect to EV3, disconnect by quitting scratch link. Restart scratch link, click the notification  to reconnect. Successfully connect. Then quit scratch link again and it doesn’t actually think it is disconnected. @picklesrus 
* [x] Unable to test wedo reconnection. Was unable to connect to WeDo after removing old Scratch Link and installing the latest Scratch Link from the wedo page. (both safari and chrome), EV3 on chrome was ok. @chrisgarrity 

### From Play Test
* [x] When Edge asks for microphone permissions, the prompt is at the *bottom* of the window. But we point to the top left when we tell the user (in the record sound modal) to grant permissions. @benjiwheeler 
* [x] The preview page (community view) gets ‘oops’ BSOD if the project includes the text2speech extension. But loads fine if you go directly to the editor.
OK: https://scratch.ly/preview/1300000210/editor/
Not OK: https://scratch.ly/preview/1300000210/ @kchadha @chrisgarrity 

Device | Browser | Name
-- | -- | --
Windows* | Chrome | Paul
Mac | Chrome | FORBIDDEN!!!!!!!!
iPad** | Safari | Karishma
Chromebook | Chrome | KathyThis was the silver samsungChrome OSVersion 69.0.3497.120 (Official Build) (32-bit)
Windows* | Firefox |  
Android Tablet | Chrome | Ben
Windows* | Edge | Eric
Mac | Safari | Chrisg
Mac | Firefox | katelyn

**Comment by ericrosenbaum** [comment] 2018-11-14 17:00
Filed:
https://github.com/LLK/scratch-blocks/issues/1783
https://github.com/LLK/scratch-gui/issues/3769

**Comment by ericrosenbaum** [comment] 2018-11-14 17:00
I was unable to reproduce this one, using Scratch Link 1.1.9:
"Connect to EV3, disconnect by quitting scratch link. Restart scratch link, click the notification to reconnect. Successfully connect. Then quit scratch link again and it doesn’t actually think it is disconnected. @picklesrus"

**Comment by ericrosenbaum** [comment] 2018-11-14 17:03
I was unable to reproduce this one, using Scratch Link 1.1.9:
"Unable to test wedo reconnection. Was unable to connect to WeDo after removing old Scratch Link and installing the latest Scratch Link from the wedo page. (both safari and chrome), EV3 on chrome was ok. @chrisgarrity"

**Comment by ericrosenbaum** [comment] 2018-11-14 19:24
Filed https://github.com/LLK/scratch-gui/issues/3770

**Comment by ericrosenbaum** [comment] 2018-11-14 23:03
"The preview page (community view) gets ‘oops’ BSOD if the project includes the text2speech" is fixed by https://github.com/LLK/scratch-www/pull/2313

**Closed** 2018-11-14 23:03 UTC
Labels: smoke-testing
