### ISSUE TITLE
The list comes above the listening block

### ISSUE THREAD

**Issue by T-taku** [LLK/scratch-gui#4372] opened 2019-01-17 09:01 UTC
![default](https://user-images.githubusercontent.com/39856622/51306887-b87fd700-1a81-11e9-8879-7c7bc6a819cd.PNG)

Lists will come on top of this listening block....

**Comment by apple502j** [comment] 2019-01-17 10:59
Duplicate of #4269

**Comment by thisandagain** [comment] 2019-01-17 20:56
Tracking in https://github.com/LLK/scratch-gui/issues/4269

**Closed by thisandagain** 2019-01-17 20:56 UTC
