### ISSUE TITLE
Block is not keeping translation

### ISSUE THREAD

**Issue by sobreira** [LLK/scratch-gui#5490] opened 2020-02-29 11:39 UTC
### Expected Behavior
Keep translation when move block to scripting rea

### Actual Behavior
Block lost its translation when move to scripting area
Block `SENSING_OF`  the variable is  `SENSING_OF_BACKDROPNUMBER` 

### Steps to Reproduce
*Change language to any language you want
* Drag the block `SENSING_OF`  and drop to scripting area
* note that during this phase block keeps to english translation #backdrop
* If block change back to translated language

![erroronblock](https://user-images.githubusercontent.com/5200448/75606736-9d79f600-5ace-11ea-9cf5-85fdc7d62312.gif)

### Operating System and Browser
Win10

**Comment by apple502j** [comment] 2020-02-29 11:47
Duplicate of #4209

**Comment by BryceLTaylor** [comment] 2020-03-03 16:48
Tracking in #4209

**Closed by BryceLTaylor** 2020-03-03 16:48 UTC
