### ISSUE TITLE
full screen mode shows block inputs

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-gui#2113] opened 2018-05-21 17:57 UTC
### Expected Behavior

_Please describe what should happen_
full screen mode only shows the player and the green flag and stop

### Actual Behavior

_Describe what actually happens_
![alt text](https://i.gyazo.com/7b37bcf9e69fb6ee52fe4bd7e4ac7a7e.gif)
a input will show
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
add block with number input, go in full screen
### Operating System and Browser

chrome windows 10

**Comment by towerofnix** [comment] 2018-05-21 18:08
Duplicate of #2009.

**Comment by paulkaplan** [comment] 2018-05-21 19:00
Closing as a duplicate of #2009

**Closed by paulkaplan** 2018-05-21 19:00 UTC
