### ISSUE TITLE
Difficult to minimize/maximize comments on ios

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#2223] opened 2018-06-01 21:21 UTC
### Expected Behavior

Tapping the dropdown arrow on a comment should toggle it between minimized and maximized easily.

### Actual Behavior

It's hard to tap the arrow and so it doesn't minimize easily.  Once it's minimized it is almost impossible to maximize again.

### Steps to Reproduce

Load a project that has a comment in it attached to blocks and maximized
Click on the dropdown arrow to minimize the comment
Note: it doesn't always minimize on the first try.
Continue to tap it until it actually minimizes
Tap the arrow again to maximize
Note: It's basically impossible to maximize it again.

### Operating System and Browser

safari on ios

**Comment by picklesrus** [comment] 2018-10-04 14:10
Closing as duplicate of https://github.com/LLK/scratch-gui/issues/2288

**Closed by picklesrus** 2018-10-04 14:10 UTC
Labels: bug, ios, safari
