### ISSUE TITLE
New blocks that allow user to change width and height in sprites?

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#2740] opened 2018-07-28 14:13 UTC
Could there be blocks in the Looks section that change a sprite's width or height, without scaling the entire sprite?

(Another feature request that some attendees of the 2018 Scratch Conference asked for. I'm sure this has been discussed in the past... it struck me as a request that is in that useful-but-not-confusing sweet spot :) )

**Comment by Kenny2github** [comment] 2018-07-28 15:34
Duplicate of LLK/scratch-vm#982 which supersedes LLK/scratch-vm#249

**Comment by thisandagain** [comment] 2018-07-31 12:36
Tracking in https://github.com/LLK/scratch-vm/issues/982

**Closed by thisandagain** 2018-07-31 12:36 UTC
Labels: feature, prio-low
