### ISSUE TITLE
Variable monitor context menus are off the screen

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#2088] opened 2018-05-17 18:50 UTC
### Expected Behavior

Context menus are in the right place.

### Actual Behavior

Too far to the right and huge.

### Steps to Reproduce

1. Show a variable
2. Right click on the monitor

### Operating System and Browser

Windows 10 Chrome 66.0.3359.181

**Comment by kyleplo** [comment] 2018-05-17 18:51
Oh, and I also noticed they no longer work at all in normal mode.

**Comment by towerofnix** [comment] 2018-05-19 19:39
Another thing - the actual expected behavior should be that the context menu doesn't show up at all in fullscreen, because fullscreen is basically a "player mode" (so in 2.0's fullscreen, monitor context menus don't show up). But this issue should still be kept open for fixing the offset issue outside of fullscreen.

**Comment by paulkaplan** [comment] 2018-05-21 15:18
This is fixed by https://github.com/LLK/scratch-gui/pull/2102, which makes the context menu not accessible in fullscreen mode (per 2.0) and also fix the positioning of the context menu in editor mode. Thanks for looking into this @kyleplo and @towerofnix

**Closed** 2018-05-21 16:08 UTC
Labels: has-patch
