### ISSUE TITLE
Thermometer menu hover state is confusing with touch devices

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-gui#2257] opened 2018-06-05 19:47 UTC
### Expected Behavior

_Please describe what should happen_
While using an iPad, it should be clear what to do to e.g., record a new sound.

### Actual Behavior

_Describe what actually happens_
The tooltip that pops up when you tap an item in the menu looks like a menu you can click, but if you tap it, it closes the menu and nothing happens.

![record](https://media.giphy.com/media/ukNZkzL3Vjr8Enizy2/giphy.gif)

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
iOS 11 Safari 11

**Comment by picklesrus** [comment] 2018-10-04 14:41
This is a duplicate of https://github.com/LLK/scratch-gui/issues/2720. Closing.

**Closed by picklesrus** 2018-10-04 14:41 UTC
Labels: needs-discussion, needs-triage, touch
