### ISSUE TITLE
Renaming list doesn't rename monitor

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-gui#4330] opened 2019-01-12 13:53 UTC
### Expected Behavior

The monitor gets renamed with the list.

### Actual Behavior

It doesn't.

### Steps to Reproduce

Create a list, show the monitor, and rename

### Operating System and Browser

Windows Chrome

**Comment by towerofnix** [comment] 2019-01-12 16:42
Duplicate of #4098.

**Closed** 2019-01-12 17:59 UTC
