### ISSUE TITLE
The comments didn`t show at the right place when project loaded

### ISSUE THREAD

**Issue by Yezzle** [LLK/scratch-gui#4776] opened 2019-04-25 10:17 UTC
1. create project and add some comments like this:
![image](https://user-images.githubusercontent.com/29877797/56728142-b87c2b00-6784-11e9-9a7a-61ef9160a42d.png)
2. then drag the block left and then comment will move too(Do not move comment)
![image](https://user-images.githubusercontent.com/29877797/56728323-1b6dc200-6785-11e9-8a1b-17a0c76b24ae.png)
3. save the project to your computer and load it, you’ll see the comment position relative to the block changed.  If you move the block to the right direction it will be look like this:
![image](https://user-images.githubusercontent.com/29877797/56728503-7e5f5900-6785-11e9-9ad4-5b3595f734a3.png)
This don`t heppends everytime,  this bothered me when many of comments added and it will be in a mess when my project loaded

**Comment by Yezzle** [comment] 2019-04-25 10:20
in fact , just move block won`t change the comment's position, the comment's position only changes then you move it

**Comment by towerofnix** [comment] 2019-04-25 11:22
The reason for this problem is being tracked here: https://github.com/LLK/scratch-blocks/issues/1566

**Comment by BryceLTaylor** [comment] 2020-07-09 20:41
Closing as duplicate of https://github.com/LLK/scratch-blocks/issues/1566

**Closed by BryceLTaylor** 2020-07-09 20:41 UTC
