### ISSUE TITLE
Clearer Error Message when logged out

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#5943] opened 2020-06-27 00:54 UTC
### Expected Behavior
If you get logged out during making a project, and you click save, you find out that you are logged out. 

### Actual Behavior
It gives this generic error. It is very unclear. 
![image](https://user-images.githubusercontent.com/64214252/85910690-57b80a80-b7ee-11ea-817e-b1bdb6f0e0ee.png)

### Steps to Reproduce
Go to a new project
Duplicate the tab
Edit the project
Log Out in the other one
Go back to the other
Edit project
Try To save
See error message
This also happens when you are logged out automatically to save server usage.

### Operating System and Browser
N/A
## Relation
This is related to llk/scratch-www#4116

## Limitations 
Right now, 

> it's currently a bit tricky to tell that you've been logged out -- we may need to do some work to make that easier to detect.
- @benjiwheeler

**Comment by apple502j** [comment] 2020-06-27 06:03
Duplicate of LLK/scratch-www#2970

**Comment by GrahamSH-LLK** [comment] 2020-06-27 14:10
>Duplicate of LLK/scratch-www#2970
>
This is a different problem. This is about telling the user that they are logged out.

**Comment by benjiwheeler** [comment] 2020-07-09 13:41
@GrahamSH-LLK thanks for adding to the conversation with this issue. I rewrote the title of https://github.com/LLK/scratch-www/issues/2970 to include this, and I'm closing this one.

**Closed by benjiwheeler** 2020-07-09 13:41 UTC
