### ISSUE TITLE
Pen draws by dragging

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-gui#1126] opened 2017-12-26 00:24 UTC
### Expected Behavior
Sprites can't draw during dragging.
### Actual Behavior
the pen draws by dragging.
### Steps to Reproduce

1. Do the "pen down" block.
2. Drag the sprite.

### Operating System and Browser
Windows7 Home Premium 64bit SP1,firefox 57.0.2

[![https://gyazo.com/7c35fd64e788e11bb78e9fe47032d02a](https://i.gyazo.com/7c35fd64e788e11bb78e9fe47032d02a.gif)](https://gyazo.com/7c35fd64e788e11bb78e9fe47032d02a)

**Comment by vutondesign** [comment] 2017-12-26 10:37
I can reproduce this on MacOS High Sierra, Chrome 63.0.3239.108.

![cu6pp8q9zy](https://user-images.githubusercontent.com/26391179/34354787-a316949c-ea28-11e7-85bd-b6fd83a725cd.gif)
(Sorry for the recording lag)

**Comment by Kenny2github** [comment] 2017-12-26 10:54
Is this a bug though? The “drag sprite” mechanism works differently from 2.0, so this might be intentional or even consistent (I don’t know for sure as I’m currently on mobile).

**Comment by kyleplo** [comment] 2017-12-26 12:52
I think it is a bug though, because this does not happen in Scratch 2.0

**Comment by mrjacobbloom** [comment] 2017-12-26 18:15
The difference between dragging a sprite in the editor and dragging a sprite in the player hasn't really been defined yet in 3.0, so incompatibilities are to be expected. However, neither editor nor player drags in 2.0 respect the pen being down (they both don't draw), so the correct behavior here is pretty clear

**Comment by paulkaplan** [comment] 2017-12-27 16:27
Closing as a duplicate of https://github.com/LLK/scratch-render/issues/144

**Closed by paulkaplan** 2017-12-27 16:27 UTC
