### ISSUE TITLE
Importing in a list and cancelling causes a file input to appear at the bottom of the page

### ISSUE THREAD

**Issue by BoomerScratch** [LLK/scratch-gui#5756] opened 2020-05-14 11:06 UTC
### Expected Behavior

Normal things happen when importing in a list and pressing cancel.

### Actual Behavior

A file input appears at the bottom of the page when you import a file in a list and press "cancel". This is probably caused in:
https://github.com/LLK/scratch-gui/blob/832cf69e5d6076896b402bc97e679b63f3f10e88/src/lib/import-csv.js#L7-L20
When you click "cancel", the "onchange" event does not fire, so it does not remove the file input. This glitch does not happen with importing sounds, costumes, sprites, etc. I have reported this a long time ago in the bugs and glitches forum, in [this topic](https://scratch.mit.edu/discuss/topic/382036/).

### Steps to Reproduce

1. Create a list.
2. Right-click it and press "import".
3. Click "cancel".
4. Click "see project page".
5. Scroll all the way down.

### Operating System and Browser

Windows NT 10.0, Chrome 81.0.4044.138

**Comment by apple502j** [comment] 2020-05-14 11:07
Duplicate of #4681

**Closed** 2020-05-15 14:44 UTC
