### ISSUE TITLE
Memory leak when the editor loads the project multiple times

### ISSUE THREAD

**Issue by SimonShiki** [LLK/scratch-gui#8213] opened 2022-04-11 12:43 UTC
### Expected Behavior
Memory should be automatically reclaimed each time it is reloaded
### Actual Behavior
the editor loads the project multiple times

### Steps to Reproduce
1. Load a large project (Make the contrast more obvious)
2. Reload the project and repeat several times
3. See error

### System Details
Chrome 100.0.4896.75 Windows 11

**Screenshots**
![image](https://user-images.githubusercontent.com/59327348/162741672-28be7a1d-179a-4bcd-b018-3357936de423.png)

**Comment by apple502j** [comment] 2022-04-11 14:40
Duplicate of #6309

**Closed as completed** 2022-04-13 01:23 UTC
