### ISSUE TITLE
Feature Request: Add support for Scratch 1.4 sound effects

### ISSUE THREAD

**Issue by Shrekfied** [LLK/scratch-gui#8357] opened 2022-05-29 23:31 UTC
Scratch 1.4 has many sound effects but they were removed in Scratch 2.0 and aren't in Scratch 3.0. You can see a few of them (there are a total of 128 sound effects) here: 

![Image](https://i.ibb.co/dPVgLwb/Screenshot-from-2022-05-29-19-19-31.png "Image")

**Comment by apple502j** [comment] 2022-05-30 08:05
Duplicate of LLK/scratch-audio#13

**Closed as completed** 2022-05-30 16:46 UTC
