### ISSUE TITLE
Empty Sound Editor State 

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-gui#3270] opened 2018-10-01 18:01 UTC
### Currently
If there are no sounds on a Sprite or the Stage and you open the Sound Editor, the editor looks blank.
![image6](https://user-images.githubusercontent.com/1088291/45649462-5eeaaa00-ba99-11e8-87cc-cea7deae4dee.png)

### Proposal
We should make this space feel more intentional and prompt the creator to add a sound. 

/cc @kathymakes

**Comment by apple502j** [comment] 2018-12-23 01:11
Duplicate of #1279

**Closed** 2019-08-02 14:36 UTC
Labels: design, enhancement, needs-triage
