### ISSUE TITLE
Uploading animated gif sometimes reorders frames

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#5138] opened 2019-08-30 18:08 UTC
### Expected Behavior

* upload animated gif
* its frames are in correct order

### Actual Behavior

* its frames are not in correct order!

### Steps to Reproduce

1. download the animated gif below (shows stars in space)
2. create new project
3. go to stage's backdrops tab
4. upload space gif
5. look at order of backdrops. If they are in correct order, delete them all and upload again.

I have sometimes seen one upload attempt succeed in resulting in correct order, but haven't seen two attempts in a row succeed.

This is the gif I've been using. It's 480x358px, with 28 frames:

![space](https://user-images.githubusercontent.com/3431616/64042203-63379800-cb2f-11e9-9c32-e03902c8ac6a.gif)

I've seen the problem occur when I upload it as a sprite, from a sprite's costume editor, or in background. It usually (not always) uploads with a few frames out of order. The order is not consistent. It seems to maybe work best if it's not showing the costumes/backdrop tab while it uploads.

Example:

![upload_bug_small](https://user-images.githubusercontent.com/3431616/64042225-6e8ac380-cb2f-11e9-8f6d-8aedaa9f836f.gif)

(It's a little blurry, but the order of frames the mouse is highlighting is space25, space28, space26)

### Operating System and Browser

Mac 10.14.5, Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by BryceLTaylor** [comment] 2022-01-05 14:55
I'm going to close this issue as a duplicate of https://github.com/LLK/scratch-gui/issues/5875 even though this one predates the other one.  It looks like the other issue has slightly more reliable repro steps and has already been prioritized.  Other than that they really are the same bug.

**Closed by BryceLTaylor** 2022-01-05 14:55 UTC
Labels: bug

**Comment by RockGuyDog** [comment] 2023-12-22 02:13
Bump this is still broken.
