### ISSUE TITLE
Saving performance is slow

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4278] opened 2019-01-07 15:48 UTC
### Expected Behavior

Saving should happen quickly and not interrupt the use of Scratch

### Actual Behavior

Saving some projects takes a long time.  This can also cause the project to freeze for long periods of time. ~10 seconds.  

This is especially true for projects with many assets, specifically ones that have a lot of sound.  

### Steps to Reproduce

Create a project with a forever loop that you can see running such as:
![screen shot 2019-01-07 at 10 30 13 am](https://user-images.githubusercontent.com/1088291/50776547-3fa1a380-1267-11e9-8c4c-e01a1fc2a2c7.png)
Run the project
Add a large sound file (~9mb) to the project
Click save now
Note: the project freezes for a long time as it saves.

This looks like it has something to do with the project saved state of the asset being set incorrectly causing the large asset to get saved every time.  Any action on the stage seems to be causing the "Save Now" button in the nav bar to become visible. 

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment] 2019-01-07 15:53
This is related to this issue about autosaving interrupting the running of the project found here: https://github.com/LLK/scratch-gui/issues/4256

**Comment by paulkaplan** [comment] 2019-01-07 18:17
I'm going to close this because I believe it is a duplicate of #4256

**Closed by paulkaplan** 2019-01-07 18:17 UTC
Labels: bug, critical, performance
