### ISSUE TITLE
Pen down does not automatically draw (without moving the sprite) on Safari and Edge

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-gui#2324] opened 2018-06-13 15:14 UTC
### Expected Behavior

the `pen down` block should leave a mark right away.

### Actual Behavior

In Safari (iOS and Mac) and Edge, the `pen down` block does not leave a mark until after you also move the sprite with a move block.

### Steps to Reproduce

Compare running:

![image](https://user-images.githubusercontent.com/1786240/41360186-1ea5381a-6efa-11e8-94a7-650b28b7a09d.png)

on Safari and Edge with Chrome and Firefox.

(Note: it doesn't matter what size the pen is set to, but setting it large makes it easy to see what is going on since it isn't behind the sprite).

### Operating System and Browser

Tested on:

Windows 10 Edge 17

iOS Safari 11.4
iOS Safari 10.3.1

MacOS 10.13.4 Safari 11.1

**Comment by paulkaplan** [comment] 2018-06-13 17:46
Interesting, this is a real disagreement in the canvas spec between webkit and chrome/firefox. This jsfiddle shows that safari doesn't draw zero-length paths, despite the cap style: https://jsfiddle.net/bqt1cf2p/8/

@cwillisf We could nudge the second x/y pair for the `drawPoint` function in renderer/src/PenSkin by a microscopic amount, offsetting one coordinate by `1e-5` seems to do the trick. Since it is canvas coordinates as far as I can tell, that should be visually identical.

**Comment by paulkaplan** [comment] 2018-06-15 20:41
Duplicate of https://github.com/LLK/scratch-gui/issues/2289

**Closed** 2018-06-15 20:41 UTC
Labels: bug, compatibility, help wanted, needs-triage, platforms
