### ISSUE TITLE
Long text in text inputs expands across the editor when active.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-gui#5847] opened 2020-06-03 02:06 UTC
### Expected Behavior
Text should be clipped as blocks are when part of them expands out of the coding workspace.

### Actual Behavior
Text expands behind the other gui elements and is not clipped

### Steps to Reproduce
1: Create a variable inside the editor.
2: Copy something _really_ long.
3: Drag the set variable to block into the workspace.
4: Paste in the string you copied.
5: Click in the general coding workspace and everything should be normal.
6: Click inside the text input in the set variable block as if you were going to type something into it. 
7: Observe how the text (but not the block) extends past the scripting area and into the rest of the editor, but the block itself works fine.

### Operating System and Browser

I think it works on everything, I use a mac though and ussally safari but I also tried with firefox.

**Comment by apple502j** [comment] 2020-06-03 02:36
Duplicate of LLK/scratch-blocks#430

**Comment by Explosion-Scratch** [comment] 2020-06-03 03:23
@apple502j Okay! Sorry, closing this one now.

**Comment by Explosion-Scratch** [comment] 2020-06-03 03:24
Sorry, I reopened this on accident.

**Closed** 2020-06-03 03:23 UTC
