### ISSUE TITLE
Reuploading 3.0 projects back into 3.0 not rendering correctly

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3086] opened 2018-09-06 15:47 UTC
### Expected Behavior
Reuploading a 3.0 project back into 3.0 should render correctly

### Actual Behavior
Created a brand new project in 3.0, downloaded it and reuploaded it back into 3.0
Noticed the following things which may or may not be an issue:
-variable slider was unchecked by default
-formatting issues sometime appear. I wasn't able to reproduce this but still wanted to include it.
<img width="1651" alt="slider unchecked default" src="https://user-images.githubusercontent.com/3812168/45168932-763cb400-b1ca-11e8-8bf1-7a0558d6bcfd.png">

### Steps to Reproduce
1. Reupload 3.0 project back into 3.0 that includes a variable slider
2. Notice the variable slider is not checked by default

### Operating System and Browser
Chrome 69, macOS High Sierra

**Comment by techwonder21** [comment] 2018-09-06 15:48
@ChampikaF

**Comment by techwonder21** [comment] 2018-09-06 18:49
@thisandagain

**Comment by thisandagain** [comment] 2018-09-06 18:54
@BryceLTaylor Can you attempt a repro?

**Comment by BryceLTaylor** [comment] 2018-09-06 21:00
I believe that it's a known issue about the monitors since no information about monitors is saved.  That work is upcoming, I believe.  

I can't reproduce the second issue by uploading.  I need more info about when it happens.  I have seen that before, but not for a while now.  I'll dig into it more soon.

**Comment by kchadha** [comment] 2018-11-07 16:37
@BryceLTaylor, could you try to find a repro of the toolbox block rendering issue?

**Comment by BryceLTaylor** [comment] 2018-11-29 16:19
@kchadha I can't reproduce the blocks rendering issue.  Also, we can save and load monitor positions now so I think we should close this.

**Closed** 2018-11-29 16:21 UTC
Labels: bug, needs-repro
