### ISSUE TITLE
Some sound blocks slows down project

### ISSUE THREAD

**Issue by Kouzeru** [LLK/scratch-gui#6559] opened 2021-01-10 06:16 UTC
### Expected Behavior

The sounds block with yield removed (instead of yielding the interpreter in the middle of scripts, it requesting redraw, just like other blocks which requires screen refresh)
![7LXEorMKHN](https://user-images.githubusercontent.com/46141631/104115638-48447d00-534c-11eb-8bad-c9312cdd5d8a.gif)
https://experiments.turbowarp.org/sounds-no-yield/471970330

Similar block which requires screen refresh
![YyHNdgBwVG](https://user-images.githubusercontent.com/46141631/104115804-4380c880-534e-11eb-8895-e2505eba756c.gif)

### Actual Behavior

https://scratch.mit.edu/projects/471970330/
![qa5xsMKyfm](https://user-images.githubusercontent.com/46141631/104115433-6315f200-534a-11eb-90d4-74b0c2c38f14.gif)

### Steps to Reproduce

Go to https://scratch.mit.edu/projects/471970330/
and see how the cat behaves.

### Operating System and Browser

_Windows 10; Google Chrome - Latest_

**Comment by apple502j** [comment] 2021-01-10 07:11
Duplicate of LLK/scratch-vm#2079

**Comment by BryceLTaylor** [comment] 2021-01-14 20:36
Closing as duplicate of LLK/scratch-vm#2079

**Closed as completed by BryceLTaylor** 2021-01-14 20:36 UTC
