### ISSUE TITLE
You can add sprites outside stage, and mess with buttons

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#5834] opened 2020-05-29 21:42 UTC
### Expected Behavior

You shouldn't be able to disable the love and favorite buttons.  
### Actual Behavior

You can, by adding a sprite outside of the stage that intercepts them. You also can detect if someone is hovering over buttons.
### Steps to Reproduce

You can. I can't find one that disables them, but [this](https://scratch.mit.edu/projects/375350431/) project detects them. I have seen one that actually works at disabling the buttons.
### Operating System and Browser
Chrome 81 Chrome OS

**Comment by apple502j** [comment] 2020-05-30 01:37
NOTE: Detector part is another bug - #5243 - and LLK/scratch-vm#2309 will patch those.

**Comment by BryceLTaylor** [comment] 2020-06-01 15:29
Closing as duplicate of #5243. If the click interception can be reproduced, please open it in a separate issue including reproduction steps.

**Closed by BryceLTaylor** 2020-06-01 15:29 UTC

**Comment by GrahamSH-LLK** [comment] 2020-06-01 15:38
See #5840
