### ISSUE TITLE
"coming soon" tooltip renders incorrectly in some positions 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-gui#1697] opened 2018-03-30 16:28 UTC
### Expected Behavior

Tooltips should render consistently

### Actual Behavior

In some cases, depending exactly where you put your mouse, the arrow attached to the tooltip renders incorrectly (see the third attempt in this gif):

![tooltip-bug](https://user-images.githubusercontent.com/567844/38145091-a5fbc330-3415-11e8-8ebb-f537d8f3f9d7.gif)

**Comment by paulkaplan** [comment] 2018-03-30 16:43
Duplicate of https://github.com/LLK/scratch-gui/issues/1691

**Closed by paulkaplan** 2018-03-30 16:43 UTC
Labels: bug
