### ISSUE TITLE
Microbit: high latency while using microbit

### ISSUE THREAD

**Issue by DeleteThisAcount** [LLK/scratch-gui#3720] opened 2018-11-10 11:33 UTC
### Expected Behavior
_micro:bit clicks have very little latency_

### Actual Behavior

micro:bit lags when buttons cliked

### Steps to Reproduce
connect microbit with scratch, load this
[Scratch Project.zip](https://github.com/LLK/scratch-gui/files/2568345/Scratch.Project.zip)
 project (change file extenstion to sb3)

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by evhan55** [comment] 2018-11-14 15:49
Hi, thank you for the report!
We would like to ask for a few more details:
- What operating system were you using?
- What browser?
- What version of Scratch Link?

Thanks again!

**Comment by DeleteThisAcount** [comment] 2018-11-15 15:20
> Hi, thank you for the report!
> We would like to ask for a few more details:
> 
> * What operating system were you using?
> * What browser?
> * What version of Scratch Link?
> 
> Thanks again!

windows 10 on a dell inspiron (chrome)
i was using scratch link downloaded 5 days ago

**Comment by evhan55** [comment] 2019-02-13 15:57
Just tested on Dell / Windows with latest Scratch Link and cannot reproduce latency issue, so closing.

**Closed by evhan55** 2019-02-13 15:57 UTC
Labels: bug, needs-repro, windows
