### ISSUE TITLE
Sprite info inputs display previous value after losing focus

### ISSUE THREAD

**Issue by neurosie** [LLK/scratch-gui#369] opened 2017-05-17 18:13 UTC
### Expected Behavior

When entering text into a field in the sprite info panel, then pressing enter, the sprite should update and the field should keep the new value. 

### Actual Behavior

The sprite updates, but the previous value is still in the field. 

### Steps to Reproduce

Change a value in one of the sprite info inputs, like "Direction".
Hit enter or click elsewhere on the page.

### Operating System and Browser

Windows 10, Chrome 58

**Comment by ethanmriley** [comment] 2017-05-17 19:17
Changing the name of the sprite updates the field to the selected option.

**Comment by paulkaplan** [comment] 2017-05-18 12:39
Thanks for the report! Confirmed that this is fixed by https://github.com/LLK/scratch-vm/pull/568, which should be merged shortly. I'll leave this open until that is merged.

**Comment by paulkaplan** [comment] 2017-05-18 15:07
Closing because LLK/scratch-vm#568 was merged which fixes this.

**Closed by paulkaplan** 2017-05-18 15:07 UTC
Labels: bug, has-patch
