### ISSUE TITLE
Project Page Goes off Page

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-gui#5728] opened 2020-05-07 22:54 UTC
### Expected Behavior

When you go to a project page, all of the text in the Instructions and Notes and Credits should be in the boxes.
### Actual Behavior

The text (at least in this case) goes off the page.

### Steps to Reproduce

1. Open [this](https://scratch.mit.edu/projects/172704222/) project. 
2. See that the text goes off the page.
![image](https://user-images.githubusercontent.com/64214252/81352245-16c83300-9094-11ea-8541-b3aced7eb264.png)

### Operating System and Browser

Chrome OS  Chrome

**Comment by apple502j** [comment] 2020-05-08 04:50
Duplicate of LLK/scratch-www#2853

**Closed** 2020-05-11 17:44 UTC
