### ISSUE TITLE
Lego BOOST extension no longer working in version 3.12.0 on MacOS 10.15.5

### ISSUE THREAD

**Issue by timgp** [LLK/scratch-gui#5967] opened 2020-07-06 14:27 UTC
### Expected Behavior

When adding the BOOST extension and clicking on the `Start searching` button, the BOOST hub should be found and connected.

### Actual Behavior

After clicking `Start searching`, the screen below is displayed almost immediately.
<img width="497" alt="Screenshot 2020-07-06 at 15 10 06" src="https://user-images.githubusercontent.com/530813/86602604-ca697880-bf9a-11ea-8950-23e57c198297.png">

Scratch Link v1.3.0 is installed and running and Bluetooth is enabled and working with other devices. I have tried rebooting, reinstalling scratching link, and using new Scratch projects rather than saved ones.

We had this working well previously. The BOOST hub can still connect successfully to the iPad so we're sure it's not the unit.

### Steps to Reproduce

1. Install Scratch Link from Mac App Store and start it
2. Install Scratch Desktop from Mac App Store
3. Click Extensions, LEGO BOOST
4. Click `Start searching`

### Operating System and Browser

Mac OS 10.15.5

**Comment by apple502j** [comment] 2020-07-06 14:43
Duplicate of LLK/scratch-link#175
(will be fixed in next scratch-link release)

**Comment by BryceLTaylor** [comment] 2020-07-07 19:35
Fixed

**Closed by BryceLTaylor** 2020-07-07 19:35 UTC
