### ISSUE TITLE
Onion skinning and animation

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-gui#5839] opened 2020-06-01 12:16 UTC
So one major feature that _all_ animation software has is onion skinning.
    Onion skinning is when the previous frame shows up translucent (and ussally red) behind the cureent frame. These layers are not selectable and do not show up in playback. This also applies to the next frame, ussally shown in blue. Since scratch isn't meant for _only_ animation this should be optional, and off by default. This could just be some sort of icon in the paint editor and this would work really well. In my opinion the transparency of the background layers should be about equal to and 80 on the ghost effect. 
    Tell me your thoughts below!

**Comment by apple502j** [comment] 2020-06-01 12:29
Duplicate of LLK/scratch-paint#904

**Comment by Explosion-Scratch** [comment] 2020-06-01 12:55
@apple502j, okay, should I close this? Or should these be merged. I have no idea how to do this stuff, I'm new to github.

**Comment by BoomerScratch** [comment] 2020-06-01 13:17
@Explosion-Scratch no, you can't merge issues. The people with write access can delete an issue, or transfer an issue. (Transferring an issue is to move an issue to a other repository)

**Comment by Explosion-Scratch** [comment] 2020-06-01 14:43
@BoomerScratch okay, that makes sense. (I guess the system could be abused otherwise)

**Closed** 2020-06-01 14:42 UTC
