### ISSUE TITLE
Sprite icons randomly goes away when you click on a sprite and never returns

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#1472] opened 2018-02-21 17:02 UTC
### Expected Behavior
Sprite icon stays the same when you click on a sprite
![iconsshow](https://user-images.githubusercontent.com/3812168/36494071-15c0755a-16ff-11e8-8ae9-5072c1287238.png)

### Actual Behavior
Sprite icons randomly goes away when you click on a sprite and never returns
![iconsdisappear](https://user-images.githubusercontent.com/3812168/36494028-f43512ec-16fe-11e8-9e27-1b8be4a6b707.png)

### Steps to Reproduce
Open a project in 3.0
Click on a sprite
Watch for the sprite icons to disappear. This may not be reproducible since it randomly happens.

### Operating System and Browser

Chrome 64

**Comment by thisandagain** [comment] 2018-02-26 19:31
Duplicate of https://github.com/LLK/scratch-gui/issues/1471

**Closed by thisandagain** 2018-02-26 19:31 UTC
