### ISSUE TITLE
Can't create custom block with %

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-gui#2726] opened 2018-07-25 01:11 UTC
### Expected Behavior
 I can
### Actual Behavior

I can't, and after closing the creating menu, the block palette looks weird

### Steps to Reproduce
create block with %
### Operating System and Browser
Chrome 66, Win 8

**Comment by paulkaplan** [comment] 2018-07-25 13:30
@cyx2015s can you include screenshots and more specific steps to reproduce. For steps, it really helps us if they are in a list that anyone can follow, including any code changes that you made, which page was loaded, which part of the page you saw the issue, and a screenshot if it makes sense.

**Comment by WorldLanguages** [comment] 2018-07-25 18:42
![image](https://user-images.githubusercontent.com/17484114/43220695-0c2cfb30-9021-11e8-9b0f-b68b54f76222.png)
![image](https://user-images.githubusercontent.com/17484114/43220724-2127f10c-9021-11e8-8cb7-67441ab99395.png)
![image](https://user-images.githubusercontent.com/17484114/43220736-2a326e30-9021-11e8-9a3d-4f0e771b6162.png)
![image](https://user-images.githubusercontent.com/17484114/43220778-442bd3bc-9021-11e8-9c19-506955806034.png)
![image](https://user-images.githubusercontent.com/17484114/43220794-51abc89e-9021-11e8-82f1-3dd0fee20a07.png)
@paulkaplan

**Comment by apple502j** [comment] 2018-07-25 20:54
Duplicate of https://github.com/LLK/scratch-blocks/issues/1368

**Comment by thisandagain** [comment] 2018-07-31 14:06
Tracking in https://github.com/LLK/scratch-blocks/issues/1368

**Closed by thisandagain** 2018-07-31 14:06 UTC
Labels: needs-info
