### ISSUE TITLE
Should unshared projects be accessible on preview?

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#2127] opened 2018-05-22 20:29 UTC
### Expected Behavior

Maybe they should 404 like Scratch does?

### Actual Behavior

Any project can be loaded

### Steps to Reproduce

1. Make a project on scratch.mit.edu. Don't share it.
2. Open the project on preview

### Operating System and Browser
Any

**Comment by towerofnix** [comment] 2018-05-22 20:49
Purely for development purposes, I'd easily say "yes". Often I want to make very small projects to quickly test 3.0 behavior, and it'd be a pain to share those all.

In terms of the community, the Scratch 3.0 preview does give a way for users to easily view other people's projects that haven't been shared (or have been unshared), but frankly, anyone who knows to use Scratch 3.0 to view an unshared project will also know that using [Phosphorus](https://phosphorus.github.io/) or other similar utilities works just as well.

**Comment by mrjacobbloom** [comment] 2018-05-22 21:17
Not to mention that there's still no way to get an unshared project's ID besides someone explicitly sharing it with you (with exceptions but whatever)

**Comment by paulkaplan** [comment] 2018-05-23 12:55
Duplicate of https://github.com/LLK/scratch-gui/issues/1801

**Closed by paulkaplan** 2018-05-23 12:55 UTC
