### ISSUE TITLE
Dragging sprite lag

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-gui#274] opened 2017-03-24 10:58 UTC
### Expected Behavior

No lag when you drag a sprite for the first time.

### Actual Behavior

When I create a new sprite and I try to drag it the player stops updating then it starts updating again 1-2 seconds later.

### Steps to Reproduce

1. Make a new sprite in Scratch GUI
2. Try dragging it in the editor player

### Operating System and Browser

Chromebook Latest Version

**Comment by paulkaplan** [comment] 2017-12-06 19:30
Duplicate of #254

**Closed by paulkaplan** 2017-12-06 19:30 UTC
Labels: bug, performance
