### ISSUE TITLE
After switching languages, the working area's scaling becomes 100%

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-gui#3277] opened 2018-10-01 22:44 UTC
### Expected Behavior
![20180830_164819_20180830164945](https://user-images.githubusercontent.com/31377746/44841073-1ea3c300-ac75-11e8-9c5c-c7fdf6e74256.gif)
### Actual Behavior
![20180830_164442_20180830164704](https://user-images.githubusercontent.com/31377746/44841081-23687700-ac75-11e8-9e70-627a0268895a.gif)
### Steps to Reproduce
Do as the image
### Operating System and Browser

Win8, Chrome 68

---
Moved from LLK/scratch-blocks#1706
/cc @cyx2015s

**Comment by julescubtree** [comment] 2018-10-30 01:40
So it seems like a root cause here is that the component unmounts, and a new component mounts, on a language switch, and the scroll/scale info in the component state is lost.
Two possible solutions, maybe?
1) Switch languages without unmounting the component.
2) Keep workspace info (scroll and scale) in redux state.
I may be able to help with option 2; not sure about 1 (at least until digging into the code more).

**Comment by thisandagain** [comment] 2018-10-30 12:42
@julescubtree Option 1 is going to be difficult to implement. My leaning would be towards option 2.

**Comment by epicfaace** [comment] 2018-12-10 17:55
I've implemented option 2 in #4011 and the [zoom setting is able to be passed into the workspace config](https://github.com/LLK/scratch-gui/pull/4011/files#diff-2d67b4b152fdb4487af9345ff9c25487R97); however, it looks like scrollX and scrollY cannot be passed into the workspace config so we cannot set the scrollX and scrollY positions to the initial positions upon changing languages. Is there a way around this?

**Comment by chrisgarrity** [comment] 2021-07-19 19:33
Closing this issue because it's no longer a problem

**Closed by chrisgarrity** 2021-07-19 19:33 UTC
Labels: Low Impact, Low Severity, bug, has patch, help wanted, localization, priority 4
