### ISSUE TITLE
3.0 "disconnect" sound no longer available

### ISSUE THREAD

**Issue by techwonder21** [LLK/scratch-gui#3839] opened 2018-11-19 20:42 UTC
### Expected Behavior

All sounds should be continue to be available
![screen shot 2018-11-16 at 8 59 23 pm](https://user-images.githubusercontent.com/3812168/48733667-4caff800-ec11-11e8-87b5-71575bca005d.png)

### Actual Behavior

The "Disconnect" sounds no longer appears in Scratch 3.0 as it did a few weeks ago.
For Hour of Code 2018, the Google CS First team casted a video around the 11/1/2018 date and showed selecting the "Disconnect" sound. Now that sound is no longer available. It also does not appear for Spanish and possibly other languages too.
![screen_shot_2018-11-19_at_11_44_29_am](https://user-images.githubusercontent.com/3812168/48733730-7cf79680-ec11-11e8-8db5-8d165a77e212.png)

### Steps to Reproduce

1. Go to Scratch 3.0 (beta website)
2. Click the "Sounds" tab
3. Search for the "Disconnect" sound
4. Notice the sound no longer exists.

### Operating System and Browser
macOS High Sierra
Chrome Version 70

**Comment by techwonder21** [comment] 2018-11-19 20:43
@ChampikaF @rschamp @thisandagain

**Comment by techwonder21** [comment] 2018-11-19 21:59
You can ignore #3838. I did not mean to submit that bug.

**Comment by apple502j** [comment] 2018-11-20 10:29
Connect and Disconnect are renamed to Start and Finish.
not a bug, [wontfix]

**Comment by Kenny2github** [comment] 2018-11-20 12:18
Actually, I think the bug is that the tutorial shows those sounds but they don't exist. Either the tutorial should be changed or the sounds should be renamed (or maybe symlinked? is that possible?)

**Comment by ericrosenbaum** [comment] 2018-11-20 18:20
Thanks for the comments- we are looking into what to do about this issue. Sorry about the confusion!

**Comment by ntlrsk** [comment] 2018-11-24 02:08
Given that the CS First tutorial for HOC depends on these sounds, the Scratch resource team agrees that the sound names Start and Finish should be renamed Connect and Disconnect (reverting the previous issue: https://github.com/LLK/scratch-gui/issues/2844 )

**Comment by paulkaplan** [comment] 2018-12-04 22:00
Fixed!

**Closed by paulkaplan** 2018-12-04 22:00 UTC
Labels: critical, enhancement
