### ISSUE TITLE
2.0 project sprite doesn't move smoothly and doesn't switch scenes 

### ISSUE THREAD

**Issue by yongabyte** [LLK/scratch-gui#689] opened 2017-09-18 19:35 UTC
### Expected Behavior
![ezgif com-optimize](https://user-images.githubusercontent.com/11052440/30560666-a0de40a2-9c86-11e7-9333-6b18bd595fb5.gif)

### Actual Behavior
1. unable to move to the right on a smooth stage (have to jump around the fallen rocket when moving left to right). 
2. sudden shrift of position when moving from right to left around the rocket.
3. unable to switch to next scene when sprite move to the edge.  
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11052440/30560677-a8aa27c4-9c86-11e7-9516-6ee3e8c56f6e.gif)

### Steps to Reproduce
Compare project in 2.0 vs. 3.0
https://llk.github.io/scratch-gui/develop/#171494108

### Operating System and Browser
Ubuntu 16.04 & Chromium 60.0.3112.113

**Comment by towerofnix** [comment] 2017-09-19 01:19
It looks like it's failing to detect the player touching the Edge sprite.

In the player sprite:

![in player sprite](https://user-images.githubusercontent.com/9948030/30571601-4e0bb9de-9cbf-11e7-8ba4-b0f859a95246.png)

In the level sprite:

![in level sprite](https://user-images.githubusercontent.com/9948030/30571600-4e01dbbc-9cbf-11e7-8d1b-9325d6c51fdf.png)

When I added a new, more opaque costume to Edge, it started working.

**Comment by towerofnix** [comment] 2017-09-19 01:22
The Edge sprite's costume is a vector image (a rectangle sitting along the right edge of the screen). When I converted the costume to a bitmap and [loaded that](https://llk.github.io/scratch-gui/develop/#175256336) in 3.0, it detected a collision with the player and the Edge sprite.

**Comment by towerofnix** [comment] 2017-09-19 01:37
The first thing I noticed with the trouble when touching the rocket is that the rocket's color is very similar to the ground. [I tried creating various costumes](https://llk.github.io/scratch-gui/develop/#175256679) to narrow the problem, and came to some surprising results:

* The "vector original" costume does not work. This is as expected, since it's the same costume.
* The "bitmap original" costume *does* work. This is interesting, because the actual color of the rocket didn't change.
* The "vector new" costume *also* works. This is interesting, because this time the difference is the color of the rocket ship.
* The "bitmap new" costume also works.

And yet in [my next debugging project](https://llk.github.io/scratch-gui/develop/#175257519), in which I isolate the problem by making the player into a "touching/not-touching the color" indicator which follows the mouse, everything behaved as expected! Surprising.

**Comment by thisandagain** [comment] 2017-09-19 11:41
Thanks for the great analysis and repro @towerofnix and @yongabyte !

**Comment by paulkaplan** [comment] 2017-12-11 20:00
So an update on this. On the original project, the edge triggering a new level seems to be working again (for me, but @towerofnix can you confirm). However just hitting "right arrow" and smoothly moving across the stage still does not work (you get "snagged" on the rocket). Here is a gif of the current state:
![edge-triggering](https://user-images.githubusercontent.com/654102/33850950-82cc9ec6-de83-11e7-961b-fb6776fec443.gif)

@cwillisf It seems like a subtle difference in the way "touching color" deals with anti-aliasing?

**Comment by towerofnix** [comment] 2017-12-11 20:46
@paulkaplan I can reproduce this as you described - moving to the edge to activate the next level does work but the player still gets snagged on the rocket (as in your gif).

Also, potentially separate (or related) issue, from this same project - these particular stars in the first level with the rocket behave weirdly:

![Marked stars](https://user-images.githubusercontent.com/9948030/33852782-a88407aa-deb3-11e7-8611-a1f6ca29579e.png)

The three red stars "kill" the player sprite, sending it back to the starting position, and the purple star acts as a solid platform (just like the ground).

This is inconsistent with your gif - when I run the project, I need to avoid specifically those stars, whereas you just jump through them (as expected; they're part of the backdrop image). An added level of difficulty, sure, but not an intended one :)

>It seems like a subtle difference in the way "touching color" deals with anti-aliasing?

I can definitely see the stars acting the way I described being related to this.

**Comment by paulkaplan** [comment] 2017-12-12 17:12
I'm going to close this and open an issue on scratch-render specifically about touching-color testing.

**Closed** 2017-12-12 17:12 UTC
Labels: critical
