### ISSUE TITLE
Exception after deleting block

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-gui#758] opened 2017-10-12 08:55 UTC
### Actual Behavior

Deleting a stack of blocks can render GUI unuseable.

### Steps to Reproduce

* Create new project
* Add an addition block within an addition block:  ( 0 + ( 0 + 0 ) )
* Duplicate the two blocks into a new stack (using right click, drag and release)

```
tried to start the same gesture twice
Blockly.WorkspaceSvg.getGesture @ lib.min.js:70
Blockly.WorkspaceSvg.onMouseDown_ @ lib.min.js:70
i @ lib.min.js:70
```

* Pick up the new stack again and drag to the block panel to delete it (exception is thrown in console)

```
lib.min.js:70 Trying to cancel a gesture recursively.`
```

* Add a new sprite, then try to navigate back to original sprite (exception thrown and unable to return to sprite)

```
Uncaught TypeError: Cannot read property 'shadow' of undefined
    at e.value (lib.min.js:17)
    at e.value (lib.min.js:17)
    at lib.min.js:17
    at Array.map (<anonymous>)
    at e.value (lib.min.js:17)
    at t.value (lib.min.js:17)
    at t.value (lib.min.js:17)
    at t.value (lib.min.js:75)
    at Object.o [as onClick] (lib.min.js:7)
    at t.value (lib.min.js:53)
```
### Operating System and Browser

Chrome (latest) on Windows 10 PC

**Comment by jwzimmer** [comment] 2017-10-13 21:18
I think https://github.com/LLK/scratch-gui/issues/759 may be a dupe of this issue? If so, we can close it.

I encountered my blocks disappearing (the project still played, but the blocks associated with the sprite were no longer visible) on 10/11/17, using Chrome, Mac, at https://ericrosenbaum.github.io/scratch-gui/extensions-oct2017/.

The error in the console was:
```
Uncaught TypeError: Cannot read property 'shadow' of undefined
```

A little bit before that, I had encountered:
```
tried to start the same gesture twice, Blockly.WorkspaceSvg.getGesture @ lib.min.js:139591
```
... When I was duplicating message blocks. The project froze - it had been playing; after I duplicated the blocks, it froze. I was sending the same message in fairly quick succession; not sure if that could be relevant.

Since both of these errors were encountered in this issue (and https://github.com/LLK/scratch-gui/issues/759) I'm putting it here.

**Comment by Kenny2github** [comment] 2017-10-14 02:48
When I tried this, I got a slightly different error message:
```Trying to cancel a gesture recursively.

tried to start the same gesture twice

Uncaught TypeError: Cannot read property 'getGesture' of null
    at Blockly.BlockSvg.onMouseDown_ (lib.min.js:78)
    at SVGGElement.i (lib.min.js:78)

Trying to cancel a gesture recursively.

Uncaught TypeError: Cannot read property 'next' of undefined
    at e.value (lib.min.js:6)
    at e.value (lib.min.js:6)
    at e.value (lib.min.js:6)
    at t.value (lib.min.js:6)
    at Blockly.WorkspaceSvg.Blockly.Workspace.fireChangeListener (lib.min.js:78)
    at Blockly.Events.fireNow_```

**Comment by jwzimmer** [comment] 2017-10-16 17:30
### Expected Behavior

Duplicating a stack of blocks should not cause errors in the console or the editor to become "frozen".

### Actual Behavior

Reported by @seotts on 10/11/17:
> (project) crashed when (I) tried to duplicate medium sized stack of blocks

### Steps to Reproduce

From @seotts:
> duplicate a stack of about 10 blocks

### Operating System and Browser

_Mac, Chrome_

**Comment by pyz1989** [comment] 2017-11-24 04:47
When I loaded a json file, first time it was ok, but second time,  I got  a message "Trying to cancel a gesture recursively." and could'nt load the project.

**Comment by rachel-fenichel** [comment] 2017-11-30 17:38
I wrote up some context for those warnings in an [issue](https://github.com/LLK/scratch-blocks/issues/1220) on scratch-blocks.  I'm copying it here for anyone who is curious:

--------------------------------

Trying to start the same gesture twice: in an ideal world all mousedowns would have corresponding mouseups. (Same for touch, etc, but that gets into questions of how touch identifiers are generated across platforms. Let's discuss it in terms of mouse events, because it's easier to talk about. )

So in the ideal world if you get a second mousedown event and you haven't gotten a mouseup event, you assume that the mousedown was a mistake of some sort and you ignore it, carrying on with the gesture you were previously tracking.

In the real world you can lose a mouseup in a few ways. On chrome you can reliably do it by mousing down, using the keyboard to change tabs, and mousing up. The original tab will never know that a mouseup occurred.

Since that would put us into an error state, the compromise is to assume that something went wrong and cancel the previous gesture, then start a new one and associate it with all following mousemove/ups. And that's fine, but it's a sign that something is weird. If it's happening a lot, it's likely I'm missing a mouseup in some other way and I want to know that and do something about it. When I finished the gesture code I wasn't 100% certain that I'd caught every case, so I left the logs in.

For instance, handling a left click and then a right click with no mouse up in the middle! That's a case that I hadn't considered, and I'm not sure what the correct behaviour is. I'm guessing the current code treats it as a right click. But what about a right click and then a left click before the right click is done?

But then I added code to make the duplicated block stick to the mouse, and that also probably causes the log. So there's a lot of noise for any signal, and I haven't seen a lot of new cases besides the one you just brought up, so removing it is fine.

---------------------------------------------

Trying to cancel a gesture recursively: again, this seems like it's a sign that something is wrong with my code if it's happening unexpectedly. But it's expected when dragging to the flyout to delete: the gesture is ending/cancelling, and says it's time to delete the block it is dragging. Block dispose checks if the block is a target of an in-progress drag. If it is, it cancels the drag...which then tries to dispose of the block.

There's a check to break the cycle, but I wanted to know if there were recursive calls that I wasn't expecting (not during deletion on the flyout, for instance). So I left a log to keep an eye out for weird cases. Nothing major has cropped up in the last few months, so I'm also fine with removing that one.

**Closed** 2017-11-30 19:26 UTC
Labels: bug, help wanted
