### ISSUE TITLE
Undoing after deleting custom block def doesn't add the block back to the flyout

### ISSUE THREAD

**Issue by owenkaplinsky** [LLK/scratch-gui#9583] opened 2024-04-14 18:19 UTC
### Expected Behavior

Undoing after deleting custom block def **will** add the block back to the flyout

### Actual Behavior

Undoing after deleting custom block def **will not** add the block back to the flyout

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Create a custom block definition
2. Delete the definition
3. Undo

### System Details
All

**Screenshots**
![image](https://github.com/scratchfoundation/scratch-gui/assets/138824486/949d5cff-b56f-48fe-baa4-d7d52973dada)

**Comment by mxmou** [comment] 2024-04-19 17:17
Probably a duplicate of #4327

**Closed as not planned** 2024-04-19 17:21 UTC
