### ISSUE TITLE
Feature request: import images from URL

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-gui#3142] opened 2018-09-14 18:50 UTC
A lot of my images I download from the internet to my computer, then upload to Scratch. It would be nice to be able to upload via URL

**Comment by towerofnix** [comment] 2018-09-14 18:55
For Scratch 3.0 online (in a web browser), you'd have to deal with CORS, which prevents one site from requesting the data of other sites which don't explicitly allow it. (Or maybe CORS is explicit denial - I don't exactly remember, but it's to the same effect.) Either error messages would have to be shown ("scratch couldn't fetch the URL, try downloading the image yourself") or a CORS proxy could be used (ala https://crossorigin.me, but probably hosted by Scratch).

"Offline" versions of Scratch 3.0 (desktop-based / "native" app) aren't restricted by CORS so it's irrelevant there.

**Comment by apple502j** [comment] 2018-09-15 10:08
Offline is restricted by "offline", meaning you can't use Internet.

Seems rejected

**Comment by apple502j** [comment] 2018-09-15 10:13
Duplicate of #2371
(But it's costume ver...

**Comment by towerofnix** [comment] 2018-09-15 15:27
@apple502j That's why I called it "offline" - native apps can still access the internet. (Your browser, Minecraft, and Python are all native programs, but they can access the internet, right?) So no, the offline app isn't limited by being called "offline".

**Comment by thisandagain** [comment] 2018-10-12 20:11
Tracking in https://github.com/LLK/scratch-gui/issues/2371

**Closed by thisandagain** 2018-10-12 20:11 UTC
Labels: request
