### ISSUE TITLE
WebGL error on load in Chrome

### ISSUE THREAD

**Issue by kevster** [LLK/scratch-gui#380] opened 2017-05-22 09:45 UTC
### Expected Behavior

after installation scratch-gui should load without errors.

### Actual Behavior

Loading the site in Chrome 58 generates the following error (scratch-render.js):

Uncaught TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at createBufferFromTypedArray (http://localhost:8601/gui.js:98068:23)
    at http://localhost:8601/gui.js:98322:21
    at Array.forEach (native)
    at createAttribsFromArrays (http://localhost:8601/gui.js:98301:26)
    at Object.createBufferInfoFromArrays (http://localhost:8601/gui.js:98558:17)
    at RenderWebGL._createGeometry (http://localhost:8601/gui.js:107777:37)
    at new RenderWebGL (http://localhost:8601/gui.js:106901:15)
    at Stage.componentDidMount (http://localhost:8601/gui.js:67147:29)
    at http://localhost:8601/lib.min.js:19461:25
    at measureLifeCyclePerf (http://localhost:8601/lib.min.js:19271:12)

A yellow Chrome warning bar also appears: 'Rats! WebGL hit a snag.'

I only experience this in Chrome, not in Safari.

### Steps to Reproduce

load the built build/index.html in Chrome 58

### Operating System and Browser

Chrome 58 on macOS 10.12.5

**Comment by cwillisf** [comment] 2017-05-25 16:48
Duplicate of #215

**Closed by cwillisf** 2017-05-25 16:48 UTC
