### ISSUE TITLE
Dropping scripts onto another sprite doesn't work on iOS

### ISSUE THREAD

**Issue by erichake** [LLK/scratch-gui#4579] opened 2019-02-21 15:52 UTC
### Expected Behavior

On computers when you drag a sprite's script to another sprite, the target sprite moves a bit and then dropping results copy the script to the target sprite.

### Actual Behavior

On iOS this action fails and so it's impossible to copy script from sprite to sprite. May be it's the same problem on all touch devices, but I only have an iPad to test...

### Steps to Reproduce

drag and drop a sprite's script to another sprite on iOS device

### Operating System and Browser

iOS 12.1.3  Safari

**Comment by paulkaplan** [comment] 2019-03-06 18:54
@erichake yeah that is unfortunately true for all touch devices right now. I'm going to close this as a duplicate of https://github.com/LLK/scratch-gui/issues/2179

**Closed by paulkaplan** 2019-03-06 18:54 UTC
Labels: bug, ios, needs-triage, touch
