### ISSUE TITLE
'New sprite' not works for all sprites.

### ISSUE THREAD

**Issue by xmeow** [LLK/scratch-gui#32] opened 2017-01-06 08:48 UTC
In https://llk.github.io/scratch-gui/ if you click on 'New Sprite' and select a sprite in the pop over modal, only some of the sprites may rendered in the stage. 
For example 'Abby' works, but not 'Airplane' or 'Bat2'.
I am not sure if this should be an issue for gui, since not new sprite button in vm's playground.

**Comment by tmickel** [comment] 2017-01-06 18:02
Haven't verified this recently, but I think this is related to the problem I was getting at in #18. A sprite is "added", but never appears rendered on the stage, probably because it's loaded with incorrect metadata. Some sprites and costumes have JSON formats that are not being handled correctly by the VM - related to the formatting of rotation centers/bitmap resolutions which are somewhat irregular.

**Comment by paulkaplan** [comment] 2017-06-08 14:18
Closing this, can't reproduce.

**Closed by paulkaplan** 2017-06-08 14:18 UTC
Labels: bug
