### ISSUE TITLE
Can navigate away from a project with unsaved changes

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#4047] opened 2018-12-12 22:16 UTC
@thisandagain says:
Able to navigate away from the project page / editor with unsaved changes on Mac OS Firefox. 

@kathymakes says:
I’m able to “create new” and “load from my computer” when I have made unsaved changes, and it navigates away without throwing a message. We should probably have a javascript modal or something here?

### Steps to Reproduce

1) Open project 
2) Switch to editor 
3) Remix project 
4) Move block stack to trigger “dirty state” 
5) quickly navigate to “My Stuff” before saving

### Operating System and Browser

Mac Firefox

**Comment by benjiwheeler** [comment] 2018-12-22 17:30
I confirmed that the "Steps to reproduce" version of this problem has been fixed; tried Mac Firefox, and same sequence gave a popup prompt.

The rest of the issue is tracked in https://github.com/LLK/scratch-gui/issues/4061 or fixed in https://github.com/LLK/scratch-gui/pull/4134

**Closed by benjiwheeler** 2018-12-22 17:30 UTC
Labels: bug, needs-triage
