### ISSUE TITLE
This project cause Scratch crash

### ISSUE THREAD

**Issue by alexwenbj** [LLK/scratch-gui#5257] opened 2019-10-21 08:45 UTC
### Expected Behavior

Please look at this project [https://scratch.mit.edu/projects/337848962/editor](:https://scratch.mit.edu/projects/337848962/editor
)
It can run and show the codes and costumes correctly.

### Actual Behavior
It cause the Scratch crash! 

### Steps to Reproduce

Click the link above to open this project
Select the Pillar sprite
Click the Costumes tab
The left pane crashed!

![image](https://user-images.githubusercontent.com/12047524/67190143-03b88300-f422-11e9-80c2-a3c8d06ca4e0.png)

### Operating System and Browser

Mac OS 10.5 Chrome 77.0.3865.90

**Comment by EastTV** [comment] 2020-01-20 10:57
um... someone should look into this.
![image](https://user-images.githubusercontent.com/45589059/72721265-3a7f7000-3bae-11ea-954a-df2be758b5b5.png)

**Comment by B294** [comment] 2020-06-13 19:05
I see this is quite old. It’s just an idea of why it’s happening, but I highly believe it was either made in the 2.0 editor or in 2.0. Vector graphics from 2.0 can not be edited in the editor of Scratch 3.0.

**Comment by EastTV** [comment] 2020-06-18 04:59
> I see this is quite old. It’s just an idea of why it’s happening, but I highly believe it was either made in the 2.0 editor or in 2.0. Vector graphics from 2.0 can not be edited in the editor of Scratch 3.0.

Really? I could edit projects made in 2.0 just fine...

**Comment by BryceLTaylor** [comment] 2020-06-18 20:31
The issue is definitely related to costume1 of the pillar sprite.  The costume has 2 bitmap images embedded into an .svg.  It appears to have been exported from Scratch 2.0 at some point, but I can import into Scratch 3.0 other svgs with embedded bitmaps that were exported from Scratch 2, so that may not be the real problem.

**Comment by apple502j** [comment] 2020-06-19 07:26
Duplicate of LLK/scratch-svg-renderer#53

**Comment by fsih** [comment] 2020-06-19 16:14
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="245.5" height="360.296142578125" viewBox="-0.5 -0.5 245.5 360.296142578125">
  
  <image id="ID0.17029661405831575" width="2" height="2" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAADklEQVR42mNhgAIWGAMAAH4ACYwGaSAAAAAtdEVYdFNvZnR3YXJlAGJ5LmJsb29kZHkuY3J5cHRvLmltYWdlLlBORzI0RW5jb2RlcqgGf+4AAAAASUVORK5CYII=" transform="matrix(0.5,0,0,0.5,0,0)" stroke-width="1" style="image-rendering: optimizespeed; image-rendering: pixelated;"/>
  <image id="53" width="52" height="320" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAFACAYAAADzvF+IAAAIy0lEQVR42u1dS3IcRRDtjJA/YWMw3IAg2HjDlhvAATgGt+AIXAF2LL2AG3AHDgG2kSzJjkgipj9DvarXla0Zh6tVT5uypJmWu7Iz8+WrfDkXP3z7nQ/36OtiuGdfyw39+OuLw/rk8cPD+vjRuD6a1ocPxpc+mNZ3798f1pt343p7czu+/uH4+pvp++tpvbqe15txfXudrJfL9zfF9e3NuF5P77++fTf+3dvp77/88p5b6Ivnn4yWmC0zW+Risshkicur649igfmJ6NeHHP+Bsc9sWqdfT9/nIdKL77P5jfgqm/7lPl03/XHpL/RpoWXrLf0229PFgk5eD5bw8g5bdvXJko7/D5OFpp3x9Nl14hrGnmkv7rxVXOz4OvILlw8NSXShX+Ajhj7jzLCWmsYwqlrx50fDyIeG0LNv2TNt6FyrvuGFuJZextaCpSy0bLwTn3K3smXcQmEsj2IWAwImC80JGZ5h3Bpz2FBjoG8lSxXyi9WirPLQ+PXTz7+IU2g7yv3+tSzU5A399ucfh/gy83P2/V+7uoH5yZrv4z5XrOPXNy++OqyffzqyQM+n9bNnT6fvx/XZ0yeH9emTx4d15vFmFmhmh15fXo3r68vD+vebcf3n1Ztxnb5/Na1v/r1K3j9fT1EOSRisFOOlPbBBWCctCMGSv7dUzIpylRtyZFtmvgzROK2DiGUtxYzLdYllTRZiPjSQugifeYq2CRb3cn1rWVlkd8DYXfnQws95cYuPdcv6HjqYZPGd5TrgM8HrykLzTjpUsIyL5tkofb9nzKyXK9gTM1EHPkQzPCCJKBrG/MPyXCVqykKUbTGL5RlwhdwjwBILdrONWLF7C7FjGoh+FbCNLpIf+C3XO4vrdIjl8LTBhnT1dQNlCCEzLOSlLJrKQjQPgQXmZ535Qi0POTk9z/JUekGhbe5DRjBWKBiuOBUgBKivvNyAIgvVbwgwWM13nGBCtLiDM5IgKAtdsD02eIijj7Q5AdW28UKKciwPYa3P4LMFoxphc6waDWWh9RuySiXLentY1DOwjSMCuXOi6w4pkDzBNs6iJnJE2X5O1+nJh1hHia2zOrkFvYiizRBeO/E5WWidU3AkBchDbnGYTbCcFRGGfKhWsZqXeTmD11WBQtbnXe6wdyNoXRaqYC6WwY2GPYINGXjz8s8V5XgeQgvAuU6FlfEo/wYE3DHKuXwodkNgKce0RDhpRvIgVswRyWnRrSe0PSSZnLE3Fi49y1GvlnAU5apRbsFYvnHrfBUbUp8xYbltaDurj2w1uPEC1YBTyM6bimmrrmfqF21bGuXYzrPTAaTtjL2RYjyxPttuCHt08Ox1M+mDzlJBFrIQx3JGfGu9bqEScmR58PrqUwhjOcgXViuAYpyCD+t9CVhnCctx1qestqfieQsiOzxmwusOMSQiCxn2aWMeqUyi8Fp9Y7aen9RzWvUhrEihT6ES9PD32elDpb5yV89psB5icw+Ccw6wby5HGNh7ehYX6qijcQDlFWNMo5XrsaME5vcQRZgsVGN9srywUZOX+QScWtiAllI9dDfWxweC5YLPesaNz5ZxOwuH0K8PGSl0YvMtcgvn6hY4dzqToXrQ4AHato36UlqRonYiPbo7j76rK9aHPOvIPbszH4SVcdqEOlXfdq1idSvvYIVe+z99tArOj5jOi4hCnAK/ISJD2Zh/MpA24GWtWGedqvjqAcuVt9Q310OoLGZzTjfbXqxPGnQM6xjCDjGUzSYFOouWYn2iN2RFxOBerjgpl8COJ858ttovp7D4AqYlW+88ZLNNjLFJZ4LbPeQhX6dvKoeq9eOjdCZJpiyWD1XRNkQx0IBzwQ/5MSQ0rzUTm5BC7IYcZs17UHPHTvywUjWqKRdSiGE5WjoG2xYYV+0LxisjDUW5OOtjEOUsUshyTTdp6DasVC2GPIQU8rTg29IEm2AB/Fy0G9jlQ2gRzPCV4JcZOJNuWREbOiEZ1I3F81AafXLGcx1y5Z0kZU7bKdkkpBC9IV+vVzwW5PKxPmUbbT3JY5buCW2nW4cyVI8WRJkWHA+Y7vYf937z0MLKlGt+ZIOq9VH2/rQitrC2XFEOWBmS8Nm5D6unsGcIGVemBRdS4DdU7jEdapXsQHyFDUNzO6vv9FixrmO1Idovh3UQ1lcZO3QaoutpZj3Zuah8kX7EF2jwCPaTD3FOobyhvrVtN9OjWhkD+mnzEzpGCmSSn4V7cuiHURIO4TyDffqZjcU/XzWa4VnXL7GEnTiCtjukQM9rLEYqOOn6pSIHJw+ILETBdLkuOv4+ph9yY+idfA6rsFwwDy2fj+rpWasR9WTuGWWttw/lT/zQpwrE81A5WuUrSScDgc+ESvVTnaY7CxnrdCd9BV6BckaIN9ZzKl4u6kPSDzXLKUg/tBO0Lf1Qs3lI+qHdoG3ph1qtWKUfahwpZJxA+sxLP9QMUpB+qPF6SPqhdjkFkk/wBR6rYC2b9YifvxpzLVlInII4BXEK4hTEKYhTEKcgTkGcgjgFcQriFFQPiVNoPQ9pJknraFszSfaRhzSTpHUsp5kk7bM+mkmyD6SgmSTtIQWS4SvBLzOwZpJ8sDykmSR74RQ0k6R1tJ1unWaSNJOHNJOkeR/STJLWLaSZJHupWNexmmaSfDS0rZkkzXMK5Q3VTJLmkIJmkrRqIc0k2QlS0EyS1vOQZpI070NZ/0G5vuFbWd5691o3lqJc9IbUjdUqUsAdVjdWWxaSwmsvPiSFV7OsjxRee0EKjh2NFipr8s4QS/NORvrYOQtWYTlhOWE5YTlhOWE5YTlhOSGFwhZLrd9MHpJav3kfklq/cQtJrd86UsB6Rmp9cQriFMQp3LM8JLV+62hbav195CGp9VvHclLrt8/6SK2/D6QgtX57SIFk+Erwywwstf4Hy0NS6++FU5Bav3W0nW6d1PrN5CGp9Zv3Ian1W7eQ1Pp7qVjXsZrU+h8NbUut3zynUN5QqfWbQwpS67dqIan1d4IUpNZvPQ9Jrd/I139delvCVg5cpgAAAC10RVh0U29mdHdhcmUAYnkuYmxvb2RkeS5jcnlwdG8uaW1hZ2UuUE5HMjRFbmNvZGVyqAZ/7gAAAABJRU5ErkJggg==" transform="matrix(0.48076921701431274,0,0,0.48076921701431274,219.5,205.45)" stroke-width="1" style="image-rendering: optimizespeed; image-rendering: pixelated;"/>
  <image id="53" width="52" height="320" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAFACAYAAADzvF+IAAAIy0lEQVR42u1dS3IcRRDtjJA/YWMw3IAg2HjDlhvAATgGt+AIXAF2LL2AG3AHDgG2kSzJjkgipj9DvarXla0Zh6tVT5uypJmWu7Iz8+WrfDkXP3z7nQ/36OtiuGdfyw39+OuLw/rk8cPD+vjRuD6a1ocPxpc+mNZ3798f1pt343p7czu+/uH4+pvp++tpvbqe15txfXudrJfL9zfF9e3NuF5P77++fTf+3dvp77/88p5b6Ivnn4yWmC0zW+Risshkicur649igfmJ6NeHHP+Bsc9sWqdfT9/nIdKL77P5jfgqm/7lPl03/XHpL/RpoWXrLf0229PFgk5eD5bw8g5bdvXJko7/D5OFpp3x9Nl14hrGnmkv7rxVXOz4OvILlw8NSXShX+Ajhj7jzLCWmsYwqlrx50fDyIeG0LNv2TNt6FyrvuGFuJZextaCpSy0bLwTn3K3smXcQmEsj2IWAwImC80JGZ5h3Bpz2FBjoG8lSxXyi9WirPLQ+PXTz7+IU2g7yv3+tSzU5A399ucfh/gy83P2/V+7uoH5yZrv4z5XrOPXNy++OqyffzqyQM+n9bNnT6fvx/XZ0yeH9emTx4d15vFmFmhmh15fXo3r68vD+vebcf3n1Ztxnb5/Na1v/r1K3j9fT1EOSRisFOOlPbBBWCctCMGSv7dUzIpylRtyZFtmvgzROK2DiGUtxYzLdYllTRZiPjSQugifeYq2CRb3cn1rWVlkd8DYXfnQws95cYuPdcv6HjqYZPGd5TrgM8HrykLzTjpUsIyL5tkofb9nzKyXK9gTM1EHPkQzPCCJKBrG/MPyXCVqykKUbTGL5RlwhdwjwBILdrONWLF7C7FjGoh+FbCNLpIf+C3XO4vrdIjl8LTBhnT1dQNlCCEzLOSlLJrKQjQPgQXmZ535Qi0POTk9z/JUekGhbe5DRjBWKBiuOBUgBKivvNyAIgvVbwgwWM13nGBCtLiDM5IgKAtdsD02eIijj7Q5AdW28UKKciwPYa3P4LMFoxphc6waDWWh9RuySiXLentY1DOwjSMCuXOi6w4pkDzBNs6iJnJE2X5O1+nJh1hHia2zOrkFvYiizRBeO/E5WWidU3AkBchDbnGYTbCcFRGGfKhWsZqXeTmD11WBQtbnXe6wdyNoXRaqYC6WwY2GPYINGXjz8s8V5XgeQgvAuU6FlfEo/wYE3DHKuXwodkNgKce0RDhpRvIgVswRyWnRrSe0PSSZnLE3Fi49y1GvlnAU5apRbsFYvnHrfBUbUp8xYbltaDurj2w1uPEC1YBTyM6bimmrrmfqF21bGuXYzrPTAaTtjL2RYjyxPttuCHt08Ox1M+mDzlJBFrIQx3JGfGu9bqEScmR58PrqUwhjOcgXViuAYpyCD+t9CVhnCctx1qestqfieQsiOzxmwusOMSQiCxn2aWMeqUyi8Fp9Y7aen9RzWvUhrEihT6ES9PD32elDpb5yV89psB5icw+Ccw6wby5HGNh7ehYX6qijcQDlFWNMo5XrsaME5vcQRZgsVGN9srywUZOX+QScWtiAllI9dDfWxweC5YLPesaNz5ZxOwuH0K8PGSl0YvMtcgvn6hY4dzqToXrQ4AHato36UlqRonYiPbo7j76rK9aHPOvIPbszH4SVcdqEOlXfdq1idSvvYIVe+z99tArOj5jOi4hCnAK/ISJD2Zh/MpA24GWtWGedqvjqAcuVt9Q310OoLGZzTjfbXqxPGnQM6xjCDjGUzSYFOouWYn2iN2RFxOBerjgpl8COJ858ttovp7D4AqYlW+88ZLNNjLFJZ4LbPeQhX6dvKoeq9eOjdCZJpiyWD1XRNkQx0IBzwQ/5MSQ0rzUTm5BC7IYcZs17UHPHTvywUjWqKRdSiGE5WjoG2xYYV+0LxisjDUW5OOtjEOUsUshyTTdp6DasVC2GPIQU8rTg29IEm2AB/Fy0G9jlQ2gRzPCV4JcZOJNuWREbOiEZ1I3F81AafXLGcx1y5Z0kZU7bKdkkpBC9IV+vVzwW5PKxPmUbbT3JY5buCW2nW4cyVI8WRJkWHA+Y7vYf937z0MLKlGt+ZIOq9VH2/rQitrC2XFEOWBmS8Nm5D6unsGcIGVemBRdS4DdU7jEdapXsQHyFDUNzO6vv9FixrmO1Idovh3UQ1lcZO3QaoutpZj3Zuah8kX7EF2jwCPaTD3FOobyhvrVtN9OjWhkD+mnzEzpGCmSSn4V7cuiHURIO4TyDffqZjcU/XzWa4VnXL7GEnTiCtjukQM9rLEYqOOn6pSIHJw+ILETBdLkuOv4+ph9yY+idfA6rsFwwDy2fj+rpWasR9WTuGWWttw/lT/zQpwrE81A5WuUrSScDgc+ESvVTnaY7CxnrdCd9BV6BckaIN9ZzKl4u6kPSDzXLKUg/tBO0Lf1Qs3lI+qHdoG3ph1qtWKUfahwpZJxA+sxLP9QMUpB+qPF6SPqhdjkFkk/wBR6rYC2b9YifvxpzLVlInII4BXEK4hTEKYhTEKcgTkGcgjgFcQriFFQPiVNoPQ9pJknraFszSfaRhzSTpHUsp5kk7bM+mkmyD6SgmSTtIQWS4SvBLzOwZpJ8sDykmSR74RQ0k6R1tJ1unWaSNJOHNJOkeR/STJLWLaSZJHupWNexmmaSfDS0rZkkzXMK5Q3VTJLmkIJmkrRqIc0k2QlS0EyS1vOQZpI070NZ/0G5vuFbWd5691o3lqJc9IbUjdUqUsAdVjdWWxaSwmsvPiSFV7OsjxRee0EKjh2NFipr8s4QS/NORvrYOQtWYTlhOWE5YTlhOWE5YTlhOSGFwhZLrd9MHpJav3kfklq/cQtJrd86UsB6Rmp9cQriFMQp3LM8JLV+62hbav195CGp9VvHclLrt8/6SK2/D6QgtX57SIFk+Erwywwstf4Hy0NS6++FU5Bav3W0nW6d1PrN5CGp9Zv3Ian1W7eQ1Pp7qVjXsZrU+h8NbUut3zynUN5QqfWbQwpS67dqIan1d4IUpNZvPQ9Jrd/I139delvCVg5cpgAAAC10RVh0U29mdHdhcmUAYnkuYmxvb2RkeS5jcnlwdG8uaW1hZ2UuUE5HMjRFbmNvZGVyqAZ/7gAAAABJRU5ErkJggg==" transform="matrix(0.48076924681663513,0,0,-0.48076924681663513,219.5,160.25)" stroke-width="1" style="image-rendering: optimizespeed; image-rendering: pixelated;"/>
</svg>

**Comment by fsih** [comment] 2020-06-19 16:14
There's also 2 things with id="53"...

Thanks! Closing as dupe

**Closed by fsih** 2020-06-19 16:14 UTC
Labels: High Severity, Low Impact, priority 3

**Comment by xacary71-dotcom** [comment] 2026-04-07 03:11
Nah look at this
