### ISSUE TITLE
Updating a variable's display state does not mark project as "dirty" for saving purposes

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-gui#7886] opened 2021-12-02 03:53 UTC
### Expected Behavior

1. Check or uncheck the display state of a variable
2. Project becomes "dirty" and "Save Now" appears

### Actual Behavior

1. Check or uncheck the display state of a variable
2. Project does NOT become "dirty", "Save Now" does NOT appear

### Steps to Reproduce

1. be logged in
2. create project
3. save so that "Save now" does not appear anymore
4. find the "my variable" variable in the code library
5. check "my variable"
6. note that "Save now" still does not appear 

![dirty](https://user-images.githubusercontent.com/3431616/144354662-c2c63ec8-17b9-4866-b2f7-8a3207196ecd.gif)

**Comment by apple502j** [comment] 2021-12-02 12:02
Duplicate of LLK/scratch-vm#2025

**Comment by BryceLTaylor** [comment] 2021-12-02 16:52
This seems more of a duplicate of https://github.com/LLK/scratch-vm/issues/2021 than 2025.  Either way, I'm going to close this one.

**Closed as completed by BryceLTaylor** 2021-12-02 16:52 UTC
Labels: Low Severity, Medium Impact
