### ISSUE TITLE
After adding a costume blocks will sometimes be shrunk (running Scratch GUI in Electron)

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-gui#301] opened 2017-04-06 18:01 UTC
### Expected Behavior

_They are not shrunk._

### Actual Behavior

_They are shrunk._

### Steps to Reproduce

_Download a copy of Scratch 3.0 in Electron (https://thebrokenrail.github.io/Scratch3Builder and https://github.com/TheBrokenRail/Scratch3Builder), open it, add a costume, and look at the blocks (Sometimes doesn't work)_

### Operating System and Browser

_Windows 10 Electron_

### Screenshot

![guibug](https://cloud.githubusercontent.com/assets/17478432/24768701/933222c0-1ad1-11e7-9ce2-9aa804d16fad.PNG)

**Comment by Airhogs777** [comment] 2017-04-06 20:03
possible dupe of #270 ?

**Comment by paulkaplan** [comment] 2017-04-19 19:24
Closing this as it is a dupe of https://github.com/LLK/scratch-gui/issues/270

**Closed by paulkaplan** 2017-04-19 19:24 UTC
