### ISSUE TITLE
Impossible to scroll with scroll bars in paint editor on touch

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#3088] opened 2018-09-06 17:52 UTC
### Expected Behavior

If you touch on the scroll bars in the paint editor and drag them the paint editor should scroll.

### Actual Behavior

You use whatever tool you have selected on the paint editor and it doesn't scroll.

### Steps to Reproduce

Open the paint editor
Ensure you are zoomed in
Touch and drag the scroll bars on the paint editor
Note: you don't scroll, you do use whatever the tool is that you had selected.

### Operating System and Browser

Safari on ipad
Chrome on Android

**Comment by picklesrus** [comment] 2018-10-04 15:06
Closing as duplicate of https://github.com/LLK/scratch-paint/issues/703

**Closed by picklesrus** 2018-10-04 15:06 UTC
Labels: android, bug, ios, touch
