### ISSUE TITLE
Can't erase text in the vector editor with the erase tool

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-gui#1700] opened 2018-03-30 17:39 UTC
Expected Behavior
I'm not sure if this should happen or not, but my instinct is that after entering text you should be able to erase it with the eraser tool.

Actual Behavior
If you use the eraser tool on some text, it gives the appearance that it will erase by drawing it's white line over it, but when you let go of the button it doesn't delete.

It seems that by covering the text with the white line it gives the impression that it will erase the text, whether it's supposed to do that or not.

**Comment by fsih** [comment] 2018-05-30 15:44
Dupe of https://github.com/LLK/scratch-paint/issues/406

**Closed by fsih** 2018-05-30 15:44 UTC
Labels: needs-discussion
